// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var sisyfox = sisyfox || {};

/**
 * @const
 * @namespace
 */
sisyfox.request = sisyfox.request || {};

/**
 * @enum
 */
sisyfox.request.Payload = {
  NONE: 0,
  Info: 1,
  AddScore: 2,
  GetScore: 3,
  GetScoreRange: 4,
  SetLiveData: 5,
  GetLiveData: 6,
  AddUser: 7,
  GetUser: 8,
  SetUser: 9,
  GetCurrentUser: 10,
  GetUserRange: 11,
  RemoveUser: 12,
  UnsetUser: 13,
  AddLocation: 14,
  GetLocation: 15,
  SetSetting: 16,
  GetSetting: 17,
  GetSettings: 18,
  Trigger: 19,
  AddDmxDevice: 20,
  RemoveDmxDevice: 21,
  AddDmxDeviceChannel: 22,
  RemoveDmxDeviceChannel: 23,
  AddDmxChannelRule: 24,
  RemoveDmxChannelRule: 25,
  AddDmxDeviceSetting: 26,
  RemoveDmxDeviceSetting: 27,
  AddDmxRuleRangeSetting: 28,
  AddDmxRuleBoolSetting: 29,
  RemoveDmxRuleSetting: 30,
  ChangeDmxDeviceSettingValue: 31,
  GetDmxDevice: 32,
  GetDmxDeviceChannel: 33,
  GetDmxChannelRule: 34,
  GetDmxDeviceSetting: 35,
  GetDmxRuleSetting: 36,
  GetDmxDeviceRange: 37,
  GetDmxDeviceChannelRange: 38,
  GetDmxChannelRuleRange: 39,
  GetDmxDeviceSettingRange: 40,
  GetDmxRuleSettingRange: 41,
  SetDmxDeviceMode: 42
};

/**
 * @enum
 */
sisyfox.request.EndReason = {
  WIN: 0,
  MAP_BOARDER: 1,
  COLLISION: 2,
  INSTANT_LOSS_ANGLE: 3,
  GROUND_DIST: 4,
  TO_STEEP: 5,
  FLASH: 6,
  UNDERWATER: 7
};

/**
 * @enum
 */
sisyfox.request.SettingType = {
  GAME_LANGUAGE: 0,
  INTERFACE_LANGUAGE: 1,
  SOUND_LEVEL: 2,
  COMPETITION_MODE: 3,
  WORLD: 64,
  LEVEL: 65,
  DIFFICULTY: 66,
  GAME_MODE: 67,
  MAX_COLLECT_WORLD: 68,
  MAX_COLLECT_LEVEL: 69,
  GEM_SCORE: 70,
  GAME_ACTIVE: 128
};

/**
 * @enum
 */
sisyfox.request.TriggerType = {
  NEW_ROUND: 0
};

/**
 * @enum
 */
sisyfox.request.DmxChannelRuleType = {
  HEIGHT: 0,
  TIME: 1,
  PITCH: 2
};

/**
 * @enum
 */
sisyfox.request.DmxDeviceSettingType = {
  RANGE: 0,
  BOOL: 1
};

/**
 * @enum
 */
sisyfox.request.DmxDeviceMode = {
  TEST: 0,
  DISABLED: 1
};

/**
 * @constructor
 */
sisyfox.request.Version = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.Version}
 */
sisyfox.request.Version.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {number}
 */
sisyfox.request.Version.prototype.high = function() {
  return this.bb.readUint8(this.bb_pos);
};

/**
 * @returns {number}
 */
sisyfox.request.Version.prototype.low = function() {
  return this.bb.readUint8(this.bb_pos + 1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} high
 * @param {number} low
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.Version.createVersion = function(builder, high, low) {
  builder.prep(1, 2);
  builder.writeInt8(low);
  builder.writeInt8(high);
  return builder.offset();
};

/**
 * @constructor
 */
sisyfox.request.Root = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.Root}
 */
sisyfox.request.Root.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.Root=} obj
 * @returns {sisyfox.request.Root}
 */
sisyfox.request.Root.getRootAsRoot = function(bb, obj) {
  return (obj || new sisyfox.request.Root).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {sisyfox.request.Version=} obj
 * @returns {sisyfox.request.Version|null}
 */
sisyfox.request.Root.prototype.version = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new sisyfox.request.Version).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @returns {number}
 */
sisyfox.request.Root.prototype.messageId = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @returns {sisyfox.request.Payload}
 */
sisyfox.request.Root.prototype.payloadType = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? /** @type {sisyfox.request.Payload} */ (this.bb.readUint8(this.bb_pos + offset)) : sisyfox.request.Payload.NONE;
};

/**
 * @param {flatbuffers.Table} obj
 * @returns {?flatbuffers.Table}
 */
sisyfox.request.Root.prototype.payload = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.Root.startRoot = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} versionOffset
 */
sisyfox.request.Root.addVersion = function(builder, versionOffset) {
  builder.addFieldStruct(0, versionOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} messageId
 */
sisyfox.request.Root.addMessageId = function(builder, messageId) {
  builder.addFieldInt16(1, messageId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {sisyfox.request.Payload} payloadType
 */
sisyfox.request.Root.addPayloadType = function(builder, payloadType) {
  builder.addFieldInt8(2, payloadType, sisyfox.request.Payload.NONE);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} payloadOffset
 */
sisyfox.request.Root.addPayload = function(builder, payloadOffset) {
  builder.addFieldOffset(3, payloadOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.Root.endRoot = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
sisyfox.request.Root.finishRootBuffer = function(builder, offset) {
  builder.finish(offset);
};

/**
 * @constructor
 */
sisyfox.request.Info = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.Info}
 */
sisyfox.request.Info.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.Info=} obj
 * @returns {sisyfox.request.Info}
 */
sisyfox.request.Info.getRootAsInfo = function(bb, obj) {
  return (obj || new sisyfox.request.Info).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.Info.startInfo = function(builder) {
  builder.startObject(0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.Info.endInfo = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
sisyfox.request.AddScore = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.AddScore}
 */
sisyfox.request.AddScore.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.AddScore=} obj
 * @returns {sisyfox.request.AddScore}
 */
sisyfox.request.AddScore.getRootAsAddScore = function(bb, obj) {
  return (obj || new sisyfox.request.AddScore).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
sisyfox.request.AddScore.prototype.height = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.AddScore.prototype.time = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @returns {sisyfox.request.EndReason}
 */
sisyfox.request.AddScore.prototype.reason = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? /** @type {sisyfox.request.EndReason} */ (this.bb.readUint8(this.bb_pos + offset)) : sisyfox.request.EndReason.WIN;
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.AddScore.startAddScore = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} height
 */
sisyfox.request.AddScore.addHeight = function(builder, height) {
  builder.addFieldInt32(0, height, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} time
 */
sisyfox.request.AddScore.addTime = function(builder, time) {
  builder.addFieldInt32(1, time, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {sisyfox.request.EndReason} reason
 */
sisyfox.request.AddScore.addReason = function(builder, reason) {
  builder.addFieldInt8(2, reason, sisyfox.request.EndReason.WIN);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.AddScore.endAddScore = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
sisyfox.request.GetScore = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.GetScore}
 */
sisyfox.request.GetScore.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.GetScore=} obj
 * @returns {sisyfox.request.GetScore}
 */
sisyfox.request.GetScore.getRootAsGetScore = function(bb, obj) {
  return (obj || new sisyfox.request.GetScore).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
sisyfox.request.GetScore.prototype.id = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.GetScore.startGetScore = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} id
 */
sisyfox.request.GetScore.addId = function(builder, id) {
  builder.addFieldInt32(0, id, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.GetScore.endGetScore = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
sisyfox.request.GetScoreRange = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.GetScoreRange}
 */
sisyfox.request.GetScoreRange.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.GetScoreRange=} obj
 * @returns {sisyfox.request.GetScoreRange}
 */
sisyfox.request.GetScoreRange.getRootAsGetScoreRange = function(bb, obj) {
  return (obj || new sisyfox.request.GetScoreRange).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
sisyfox.request.GetScoreRange.prototype.range = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint8(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.GetScoreRange.prototype.startId = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.GetScoreRange.startGetScoreRange = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} range
 */
sisyfox.request.GetScoreRange.addRange = function(builder, range) {
  builder.addFieldInt8(0, range, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} startId
 */
sisyfox.request.GetScoreRange.addStartId = function(builder, startId) {
  builder.addFieldInt32(1, startId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.GetScoreRange.endGetScoreRange = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
sisyfox.request.AddLocation = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.AddLocation}
 */
sisyfox.request.AddLocation.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.AddLocation=} obj
 * @returns {sisyfox.request.AddLocation}
 */
sisyfox.request.AddLocation.getRootAsAddLocation = function(bb, obj) {
  return (obj || new sisyfox.request.AddLocation).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
sisyfox.request.AddLocation.prototype.startId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
sisyfox.request.AddLocation.prototype.name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.AddLocation.startAddLocation = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} startId
 */
sisyfox.request.AddLocation.addStartId = function(builder, startId) {
  builder.addFieldInt32(0, startId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} nameOffset
 */
sisyfox.request.AddLocation.addName = function(builder, nameOffset) {
  builder.addFieldOffset(1, nameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.AddLocation.endAddLocation = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
sisyfox.request.GetLocation = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.GetLocation}
 */
sisyfox.request.GetLocation.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.GetLocation=} obj
 * @returns {sisyfox.request.GetLocation}
 */
sisyfox.request.GetLocation.getRootAsGetLocation = function(bb, obj) {
  return (obj || new sisyfox.request.GetLocation).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
sisyfox.request.GetLocation.prototype.id = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.GetLocation.startGetLocation = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} id
 */
sisyfox.request.GetLocation.addId = function(builder, id) {
  builder.addFieldInt32(0, id, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.GetLocation.endGetLocation = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
sisyfox.request.LiveData = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.LiveData}
 */
sisyfox.request.LiveData.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns {number}
 */
sisyfox.request.LiveData.prototype.height = function() {
  return this.bb.readInt32(this.bb_pos);
};

/**
 * @returns {number}
 */
sisyfox.request.LiveData.prototype.time = function() {
  return this.bb.readInt32(this.bb_pos + 4);
};

/**
 * @returns {number}
 */
sisyfox.request.LiveData.prototype.pitch = function() {
  return this.bb.readInt32(this.bb_pos + 8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} height
 * @param {number} time
 * @param {number} pitch
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.LiveData.createLiveData = function(builder, height, time, pitch) {
  builder.prep(4, 12);
  builder.writeInt32(pitch);
  builder.writeInt32(time);
  builder.writeInt32(height);
  return builder.offset();
};

/**
 * @constructor
 */
sisyfox.request.SetLiveData = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.SetLiveData}
 */
sisyfox.request.SetLiveData.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.SetLiveData=} obj
 * @returns {sisyfox.request.SetLiveData}
 */
sisyfox.request.SetLiveData.getRootAsSetLiveData = function(bb, obj) {
  return (obj || new sisyfox.request.SetLiveData).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {sisyfox.request.LiveData=} obj
 * @returns {sisyfox.request.LiveData|null}
 */
sisyfox.request.SetLiveData.prototype.liveData = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? (obj || new sisyfox.request.LiveData).__init(this.bb_pos + offset, this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.SetLiveData.startSetLiveData = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} liveDataOffset
 */
sisyfox.request.SetLiveData.addLiveData = function(builder, liveDataOffset) {
  builder.addFieldStruct(0, liveDataOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.SetLiveData.endSetLiveData = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
sisyfox.request.GetLiveData = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.GetLiveData}
 */
sisyfox.request.GetLiveData.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.GetLiveData=} obj
 * @returns {sisyfox.request.GetLiveData}
 */
sisyfox.request.GetLiveData.getRootAsGetLiveData = function(bb, obj) {
  return (obj || new sisyfox.request.GetLiveData).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.GetLiveData.startGetLiveData = function(builder) {
  builder.startObject(0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.GetLiveData.endGetLiveData = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
sisyfox.request.AddUser = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.AddUser}
 */
sisyfox.request.AddUser.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.AddUser=} obj
 * @returns {sisyfox.request.AddUser}
 */
sisyfox.request.AddUser.getRootAsAddUser = function(bb, obj) {
  return (obj || new sisyfox.request.AddUser).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
sisyfox.request.AddUser.prototype.name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.AddUser.startAddUser = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} nameOffset
 */
sisyfox.request.AddUser.addName = function(builder, nameOffset) {
  builder.addFieldOffset(0, nameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.AddUser.endAddUser = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
sisyfox.request.GetUser = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.GetUser}
 */
sisyfox.request.GetUser.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.GetUser=} obj
 * @returns {sisyfox.request.GetUser}
 */
sisyfox.request.GetUser.getRootAsGetUser = function(bb, obj) {
  return (obj || new sisyfox.request.GetUser).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
sisyfox.request.GetUser.prototype.uId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.GetUser.startGetUser = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} uId
 */
sisyfox.request.GetUser.addUId = function(builder, uId) {
  builder.addFieldInt32(0, uId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.GetUser.endGetUser = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
sisyfox.request.SetUser = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.SetUser}
 */
sisyfox.request.SetUser.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.SetUser=} obj
 * @returns {sisyfox.request.SetUser}
 */
sisyfox.request.SetUser.getRootAsSetUser = function(bb, obj) {
  return (obj || new sisyfox.request.SetUser).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
sisyfox.request.SetUser.prototype.uId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.SetUser.startSetUser = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} uId
 */
sisyfox.request.SetUser.addUId = function(builder, uId) {
  builder.addFieldInt32(0, uId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.SetUser.endSetUser = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
sisyfox.request.GetCurrentUser = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.GetCurrentUser}
 */
sisyfox.request.GetCurrentUser.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.GetCurrentUser=} obj
 * @returns {sisyfox.request.GetCurrentUser}
 */
sisyfox.request.GetCurrentUser.getRootAsGetCurrentUser = function(bb, obj) {
  return (obj || new sisyfox.request.GetCurrentUser).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.GetCurrentUser.startGetCurrentUser = function(builder) {
  builder.startObject(0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.GetCurrentUser.endGetCurrentUser = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
sisyfox.request.GetUserRange = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.GetUserRange}
 */
sisyfox.request.GetUserRange.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.GetUserRange=} obj
 * @returns {sisyfox.request.GetUserRange}
 */
sisyfox.request.GetUserRange.getRootAsGetUserRange = function(bb, obj) {
  return (obj || new sisyfox.request.GetUserRange).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
sisyfox.request.GetUserRange.prototype.startUid = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.GetUserRange.prototype.range = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint8(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.GetUserRange.startGetUserRange = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} startUid
 */
sisyfox.request.GetUserRange.addStartUid = function(builder, startUid) {
  builder.addFieldInt32(0, startUid, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} range
 */
sisyfox.request.GetUserRange.addRange = function(builder, range) {
  builder.addFieldInt8(1, range, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.GetUserRange.endGetUserRange = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
sisyfox.request.RemoveUser = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.RemoveUser}
 */
sisyfox.request.RemoveUser.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.RemoveUser=} obj
 * @returns {sisyfox.request.RemoveUser}
 */
sisyfox.request.RemoveUser.getRootAsRemoveUser = function(bb, obj) {
  return (obj || new sisyfox.request.RemoveUser).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
sisyfox.request.RemoveUser.prototype.uid = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.RemoveUser.startRemoveUser = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} uid
 */
sisyfox.request.RemoveUser.addUid = function(builder, uid) {
  builder.addFieldInt32(0, uid, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.RemoveUser.endRemoveUser = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
sisyfox.request.UnsetUser = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.UnsetUser}
 */
sisyfox.request.UnsetUser.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.UnsetUser=} obj
 * @returns {sisyfox.request.UnsetUser}
 */
sisyfox.request.UnsetUser.getRootAsUnsetUser = function(bb, obj) {
  return (obj || new sisyfox.request.UnsetUser).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.UnsetUser.startUnsetUser = function(builder) {
  builder.startObject(0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.UnsetUser.endUnsetUser = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
sisyfox.request.SetSetting = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.SetSetting}
 */
sisyfox.request.SetSetting.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.SetSetting=} obj
 * @returns {sisyfox.request.SetSetting}
 */
sisyfox.request.SetSetting.getRootAsSetSetting = function(bb, obj) {
  return (obj || new sisyfox.request.SetSetting).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {sisyfox.request.SettingType}
 */
sisyfox.request.SetSetting.prototype.type = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {sisyfox.request.SettingType} */ (this.bb.readUint8(this.bb_pos + offset)) : sisyfox.request.SettingType.GAME_LANGUAGE;
};

/**
 * @returns {number}
 */
sisyfox.request.SetSetting.prototype.value = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.SetSetting.startSetSetting = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {sisyfox.request.SettingType} type
 */
sisyfox.request.SetSetting.addType = function(builder, type) {
  builder.addFieldInt8(0, type, sisyfox.request.SettingType.GAME_LANGUAGE);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} value
 */
sisyfox.request.SetSetting.addValue = function(builder, value) {
  builder.addFieldInt32(1, value, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.SetSetting.endSetSetting = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
sisyfox.request.GetSetting = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.GetSetting}
 */
sisyfox.request.GetSetting.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.GetSetting=} obj
 * @returns {sisyfox.request.GetSetting}
 */
sisyfox.request.GetSetting.getRootAsGetSetting = function(bb, obj) {
  return (obj || new sisyfox.request.GetSetting).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {sisyfox.request.SettingType}
 */
sisyfox.request.GetSetting.prototype.type = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {sisyfox.request.SettingType} */ (this.bb.readUint8(this.bb_pos + offset)) : sisyfox.request.SettingType.GAME_LANGUAGE;
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.GetSetting.startGetSetting = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {sisyfox.request.SettingType} type
 */
sisyfox.request.GetSetting.addType = function(builder, type) {
  builder.addFieldInt8(0, type, sisyfox.request.SettingType.GAME_LANGUAGE);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.GetSetting.endGetSetting = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
sisyfox.request.GetSettings = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.GetSettings}
 */
sisyfox.request.GetSettings.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.GetSettings=} obj
 * @returns {sisyfox.request.GetSettings}
 */
sisyfox.request.GetSettings.getRootAsGetSettings = function(bb, obj) {
  return (obj || new sisyfox.request.GetSettings).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.GetSettings.startGetSettings = function(builder) {
  builder.startObject(0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.GetSettings.endGetSettings = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
sisyfox.request.Trigger = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.Trigger}
 */
sisyfox.request.Trigger.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.Trigger=} obj
 * @returns {sisyfox.request.Trigger}
 */
sisyfox.request.Trigger.getRootAsTrigger = function(bb, obj) {
  return (obj || new sisyfox.request.Trigger).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {sisyfox.request.TriggerType}
 */
sisyfox.request.Trigger.prototype.type = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {sisyfox.request.TriggerType} */ (this.bb.readInt8(this.bb_pos + offset)) : sisyfox.request.TriggerType.NEW_ROUND;
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.Trigger.startTrigger = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {sisyfox.request.TriggerType} type
 */
sisyfox.request.Trigger.addType = function(builder, type) {
  builder.addFieldInt8(0, type, sisyfox.request.TriggerType.NEW_ROUND);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.Trigger.endTrigger = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
sisyfox.request.AddDmxDevice = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.AddDmxDevice}
 */
sisyfox.request.AddDmxDevice.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.AddDmxDevice=} obj
 * @returns {sisyfox.request.AddDmxDevice}
 */
sisyfox.request.AddDmxDevice.getRootAsAddDmxDevice = function(bb, obj) {
  return (obj || new sisyfox.request.AddDmxDevice).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
sisyfox.request.AddDmxDevice.prototype.name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.AddDmxDevice.startAddDmxDevice = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} nameOffset
 */
sisyfox.request.AddDmxDevice.addName = function(builder, nameOffset) {
  builder.addFieldOffset(0, nameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.AddDmxDevice.endAddDmxDevice = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
sisyfox.request.RemoveDmxDevice = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.RemoveDmxDevice}
 */
sisyfox.request.RemoveDmxDevice.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.RemoveDmxDevice=} obj
 * @returns {sisyfox.request.RemoveDmxDevice}
 */
sisyfox.request.RemoveDmxDevice.getRootAsRemoveDmxDevice = function(bb, obj) {
  return (obj || new sisyfox.request.RemoveDmxDevice).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
sisyfox.request.RemoveDmxDevice.prototype.deviceId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.RemoveDmxDevice.startRemoveDmxDevice = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} deviceId
 */
sisyfox.request.RemoveDmxDevice.addDeviceId = function(builder, deviceId) {
  builder.addFieldInt32(0, deviceId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.RemoveDmxDevice.endRemoveDmxDevice = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
sisyfox.request.AddDmxDeviceChannel = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.AddDmxDeviceChannel}
 */
sisyfox.request.AddDmxDeviceChannel.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.AddDmxDeviceChannel=} obj
 * @returns {sisyfox.request.AddDmxDeviceChannel}
 */
sisyfox.request.AddDmxDeviceChannel.getRootAsAddDmxDeviceChannel = function(bb, obj) {
  return (obj || new sisyfox.request.AddDmxDeviceChannel).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
sisyfox.request.AddDmxDeviceChannel.prototype.deviceId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.AddDmxDeviceChannel.prototype.channel = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.AddDmxDeviceChannel.prototype.norm = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readUint8(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.AddDmxDeviceChannel.prototype.test = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readUint8(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.AddDmxDeviceChannel.startAddDmxDeviceChannel = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} deviceId
 */
sisyfox.request.AddDmxDeviceChannel.addDeviceId = function(builder, deviceId) {
  builder.addFieldInt32(0, deviceId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} channel
 */
sisyfox.request.AddDmxDeviceChannel.addChannel = function(builder, channel) {
  builder.addFieldInt32(1, channel, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} norm
 */
sisyfox.request.AddDmxDeviceChannel.addNorm = function(builder, norm) {
  builder.addFieldInt8(2, norm, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} test
 */
sisyfox.request.AddDmxDeviceChannel.addTest = function(builder, test) {
  builder.addFieldInt8(3, test, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.AddDmxDeviceChannel.endAddDmxDeviceChannel = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
sisyfox.request.RemoveDmxDeviceChannel = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.RemoveDmxDeviceChannel}
 */
sisyfox.request.RemoveDmxDeviceChannel.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.RemoveDmxDeviceChannel=} obj
 * @returns {sisyfox.request.RemoveDmxDeviceChannel}
 */
sisyfox.request.RemoveDmxDeviceChannel.getRootAsRemoveDmxDeviceChannel = function(bb, obj) {
  return (obj || new sisyfox.request.RemoveDmxDeviceChannel).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
sisyfox.request.RemoveDmxDeviceChannel.prototype.deviceId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.RemoveDmxDeviceChannel.prototype.channelId = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.RemoveDmxDeviceChannel.startRemoveDmxDeviceChannel = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} deviceId
 */
sisyfox.request.RemoveDmxDeviceChannel.addDeviceId = function(builder, deviceId) {
  builder.addFieldInt32(0, deviceId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} channelId
 */
sisyfox.request.RemoveDmxDeviceChannel.addChannelId = function(builder, channelId) {
  builder.addFieldInt32(1, channelId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.RemoveDmxDeviceChannel.endRemoveDmxDeviceChannel = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
sisyfox.request.AddDmxChannelRule = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.AddDmxChannelRule}
 */
sisyfox.request.AddDmxChannelRule.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.AddDmxChannelRule=} obj
 * @returns {sisyfox.request.AddDmxChannelRule}
 */
sisyfox.request.AddDmxChannelRule.getRootAsAddDmxChannelRule = function(bb, obj) {
  return (obj || new sisyfox.request.AddDmxChannelRule).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
sisyfox.request.AddDmxChannelRule.prototype.deviceId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.AddDmxChannelRule.prototype.channelId = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {sisyfox.request.DmxChannelRuleType}
 */
sisyfox.request.AddDmxChannelRule.prototype.ruleType = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? /** @type {sisyfox.request.DmxChannelRuleType} */ (this.bb.readInt8(this.bb_pos + offset)) : sisyfox.request.DmxChannelRuleType.HEIGHT;
};

/**
 * @returns {number}
 */
sisyfox.request.AddDmxChannelRule.prototype.on = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.AddDmxChannelRule.prototype.off = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.AddDmxChannelRule.prototype.start = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.readUint8(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.AddDmxChannelRule.prototype.step = function() {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.AddDmxChannelRule.startAddDmxChannelRule = function(builder) {
  builder.startObject(7);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} deviceId
 */
sisyfox.request.AddDmxChannelRule.addDeviceId = function(builder, deviceId) {
  builder.addFieldInt32(0, deviceId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} channelId
 */
sisyfox.request.AddDmxChannelRule.addChannelId = function(builder, channelId) {
  builder.addFieldInt32(1, channelId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {sisyfox.request.DmxChannelRuleType} ruleType
 */
sisyfox.request.AddDmxChannelRule.addRuleType = function(builder, ruleType) {
  builder.addFieldInt8(2, ruleType, sisyfox.request.DmxChannelRuleType.HEIGHT);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} on
 */
sisyfox.request.AddDmxChannelRule.addOn = function(builder, on) {
  builder.addFieldInt32(3, on, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} off
 */
sisyfox.request.AddDmxChannelRule.addOff = function(builder, off) {
  builder.addFieldInt32(4, off, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} start
 */
sisyfox.request.AddDmxChannelRule.addStart = function(builder, start) {
  builder.addFieldInt8(5, start, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} step
 */
sisyfox.request.AddDmxChannelRule.addStep = function(builder, step) {
  builder.addFieldFloat32(6, step, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.AddDmxChannelRule.endAddDmxChannelRule = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
sisyfox.request.RemoveDmxChannelRule = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.RemoveDmxChannelRule}
 */
sisyfox.request.RemoveDmxChannelRule.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.RemoveDmxChannelRule=} obj
 * @returns {sisyfox.request.RemoveDmxChannelRule}
 */
sisyfox.request.RemoveDmxChannelRule.getRootAsRemoveDmxChannelRule = function(bb, obj) {
  return (obj || new sisyfox.request.RemoveDmxChannelRule).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
sisyfox.request.RemoveDmxChannelRule.prototype.deviceId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.RemoveDmxChannelRule.prototype.channelId = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.RemoveDmxChannelRule.prototype.ruleId = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.RemoveDmxChannelRule.startRemoveDmxChannelRule = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} deviceId
 */
sisyfox.request.RemoveDmxChannelRule.addDeviceId = function(builder, deviceId) {
  builder.addFieldInt32(0, deviceId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} channelId
 */
sisyfox.request.RemoveDmxChannelRule.addChannelId = function(builder, channelId) {
  builder.addFieldInt32(1, channelId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} ruleId
 */
sisyfox.request.RemoveDmxChannelRule.addRuleId = function(builder, ruleId) {
  builder.addFieldInt32(2, ruleId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.RemoveDmxChannelRule.endRemoveDmxChannelRule = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
sisyfox.request.AddDmxDeviceSetting = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.AddDmxDeviceSetting}
 */
sisyfox.request.AddDmxDeviceSetting.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.AddDmxDeviceSetting=} obj
 * @returns {sisyfox.request.AddDmxDeviceSetting}
 */
sisyfox.request.AddDmxDeviceSetting.getRootAsAddDmxDeviceSetting = function(bb, obj) {
  return (obj || new sisyfox.request.AddDmxDeviceSetting).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
sisyfox.request.AddDmxDeviceSetting.prototype.deviceId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {sisyfox.request.DmxDeviceSettingType}
 */
sisyfox.request.AddDmxDeviceSetting.prototype.settingType = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? /** @type {sisyfox.request.DmxDeviceSettingType} */ (this.bb.readInt8(this.bb_pos + offset)) : sisyfox.request.DmxDeviceSettingType.RANGE;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
sisyfox.request.AddDmxDeviceSetting.prototype.name = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns {number}
 */
sisyfox.request.AddDmxDeviceSetting.prototype.norm = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readInt8(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.AddDmxDeviceSetting.startAddDmxDeviceSetting = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} deviceId
 */
sisyfox.request.AddDmxDeviceSetting.addDeviceId = function(builder, deviceId) {
  builder.addFieldInt32(0, deviceId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {sisyfox.request.DmxDeviceSettingType} settingType
 */
sisyfox.request.AddDmxDeviceSetting.addSettingType = function(builder, settingType) {
  builder.addFieldInt8(1, settingType, sisyfox.request.DmxDeviceSettingType.RANGE);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} nameOffset
 */
sisyfox.request.AddDmxDeviceSetting.addName = function(builder, nameOffset) {
  builder.addFieldOffset(2, nameOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} norm
 */
sisyfox.request.AddDmxDeviceSetting.addNorm = function(builder, norm) {
  builder.addFieldInt8(3, norm, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.AddDmxDeviceSetting.endAddDmxDeviceSetting = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
sisyfox.request.RemoveDmxDeviceSetting = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.RemoveDmxDeviceSetting}
 */
sisyfox.request.RemoveDmxDeviceSetting.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.RemoveDmxDeviceSetting=} obj
 * @returns {sisyfox.request.RemoveDmxDeviceSetting}
 */
sisyfox.request.RemoveDmxDeviceSetting.getRootAsRemoveDmxDeviceSetting = function(bb, obj) {
  return (obj || new sisyfox.request.RemoveDmxDeviceSetting).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
sisyfox.request.RemoveDmxDeviceSetting.prototype.deviceId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.RemoveDmxDeviceSetting.prototype.settingId = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.RemoveDmxDeviceSetting.startRemoveDmxDeviceSetting = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} deviceId
 */
sisyfox.request.RemoveDmxDeviceSetting.addDeviceId = function(builder, deviceId) {
  builder.addFieldInt32(0, deviceId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} settingId
 */
sisyfox.request.RemoveDmxDeviceSetting.addSettingId = function(builder, settingId) {
  builder.addFieldInt32(1, settingId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.RemoveDmxDeviceSetting.endRemoveDmxDeviceSetting = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
sisyfox.request.AddDmxRuleRangeSetting = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.AddDmxRuleRangeSetting}
 */
sisyfox.request.AddDmxRuleRangeSetting.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.AddDmxRuleRangeSetting=} obj
 * @returns {sisyfox.request.AddDmxRuleRangeSetting}
 */
sisyfox.request.AddDmxRuleRangeSetting.getRootAsAddDmxRuleRangeSetting = function(bb, obj) {
  return (obj || new sisyfox.request.AddDmxRuleRangeSetting).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
sisyfox.request.AddDmxRuleRangeSetting.prototype.deviceId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.AddDmxRuleRangeSetting.prototype.settingId = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.AddDmxRuleRangeSetting.prototype.channelId = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.AddDmxRuleRangeSetting.prototype.ruleId = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.AddDmxRuleRangeSetting.prototype.on = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
};

/**
 * @returns {number}
 */
sisyfox.request.AddDmxRuleRangeSetting.prototype.off = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
};

/**
 * @returns {number}
 */
sisyfox.request.AddDmxRuleRangeSetting.prototype.start = function() {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
};

/**
 * @returns {number}
 */
sisyfox.request.AddDmxRuleRangeSetting.prototype.step = function() {
  var offset = this.bb.__offset(this.bb_pos, 18);
  return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.AddDmxRuleRangeSetting.startAddDmxRuleRangeSetting = function(builder) {
  builder.startObject(8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} deviceId
 */
sisyfox.request.AddDmxRuleRangeSetting.addDeviceId = function(builder, deviceId) {
  builder.addFieldInt32(0, deviceId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} settingId
 */
sisyfox.request.AddDmxRuleRangeSetting.addSettingId = function(builder, settingId) {
  builder.addFieldInt32(1, settingId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} channelId
 */
sisyfox.request.AddDmxRuleRangeSetting.addChannelId = function(builder, channelId) {
  builder.addFieldInt32(2, channelId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} ruleId
 */
sisyfox.request.AddDmxRuleRangeSetting.addRuleId = function(builder, ruleId) {
  builder.addFieldInt32(3, ruleId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} on
 */
sisyfox.request.AddDmxRuleRangeSetting.addOn = function(builder, on) {
  builder.addFieldFloat32(4, on, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} off
 */
sisyfox.request.AddDmxRuleRangeSetting.addOff = function(builder, off) {
  builder.addFieldFloat32(5, off, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} start
 */
sisyfox.request.AddDmxRuleRangeSetting.addStart = function(builder, start) {
  builder.addFieldFloat32(6, start, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} step
 */
sisyfox.request.AddDmxRuleRangeSetting.addStep = function(builder, step) {
  builder.addFieldFloat32(7, step, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.AddDmxRuleRangeSetting.endAddDmxRuleRangeSetting = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
sisyfox.request.AddDmxRuleBoolSetting = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.AddDmxRuleBoolSetting}
 */
sisyfox.request.AddDmxRuleBoolSetting.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.AddDmxRuleBoolSetting=} obj
 * @returns {sisyfox.request.AddDmxRuleBoolSetting}
 */
sisyfox.request.AddDmxRuleBoolSetting.getRootAsAddDmxRuleBoolSetting = function(bb, obj) {
  return (obj || new sisyfox.request.AddDmxRuleBoolSetting).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
sisyfox.request.AddDmxRuleBoolSetting.prototype.deviceId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.AddDmxRuleBoolSetting.prototype.settingId = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.AddDmxRuleBoolSetting.prototype.channelId = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.AddDmxRuleBoolSetting.prototype.ruleId = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.AddDmxRuleBoolSetting.prototype.on = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.AddDmxRuleBoolSetting.prototype.off = function() {
  var offset = this.bb.__offset(this.bb_pos, 14);
  return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.AddDmxRuleBoolSetting.prototype.start = function() {
  var offset = this.bb.__offset(this.bb_pos, 16);
  return offset ? this.bb.readUint8(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.AddDmxRuleBoolSetting.prototype.step = function() {
  var offset = this.bb.__offset(this.bb_pos, 18);
  return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.AddDmxRuleBoolSetting.startAddDmxRuleBoolSetting = function(builder) {
  builder.startObject(8);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} deviceId
 */
sisyfox.request.AddDmxRuleBoolSetting.addDeviceId = function(builder, deviceId) {
  builder.addFieldInt32(0, deviceId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} settingId
 */
sisyfox.request.AddDmxRuleBoolSetting.addSettingId = function(builder, settingId) {
  builder.addFieldInt32(1, settingId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} channelId
 */
sisyfox.request.AddDmxRuleBoolSetting.addChannelId = function(builder, channelId) {
  builder.addFieldInt32(2, channelId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} ruleId
 */
sisyfox.request.AddDmxRuleBoolSetting.addRuleId = function(builder, ruleId) {
  builder.addFieldInt32(3, ruleId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} on
 */
sisyfox.request.AddDmxRuleBoolSetting.addOn = function(builder, on) {
  builder.addFieldInt32(4, on, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} off
 */
sisyfox.request.AddDmxRuleBoolSetting.addOff = function(builder, off) {
  builder.addFieldInt32(5, off, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} start
 */
sisyfox.request.AddDmxRuleBoolSetting.addStart = function(builder, start) {
  builder.addFieldInt8(6, start, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} step
 */
sisyfox.request.AddDmxRuleBoolSetting.addStep = function(builder, step) {
  builder.addFieldFloat32(7, step, 0.0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.AddDmxRuleBoolSetting.endAddDmxRuleBoolSetting = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
sisyfox.request.RemoveDmxRuleSetting = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.RemoveDmxRuleSetting}
 */
sisyfox.request.RemoveDmxRuleSetting.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.RemoveDmxRuleSetting=} obj
 * @returns {sisyfox.request.RemoveDmxRuleSetting}
 */
sisyfox.request.RemoveDmxRuleSetting.getRootAsRemoveDmxRuleSetting = function(bb, obj) {
  return (obj || new sisyfox.request.RemoveDmxRuleSetting).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
sisyfox.request.RemoveDmxRuleSetting.prototype.deviceId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.RemoveDmxRuleSetting.prototype.settingId = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.RemoveDmxRuleSetting.prototype.ruleSettingId = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.RemoveDmxRuleSetting.startRemoveDmxRuleSetting = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} deviceId
 */
sisyfox.request.RemoveDmxRuleSetting.addDeviceId = function(builder, deviceId) {
  builder.addFieldInt32(0, deviceId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} settingId
 */
sisyfox.request.RemoveDmxRuleSetting.addSettingId = function(builder, settingId) {
  builder.addFieldInt32(1, settingId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} ruleSettingId
 */
sisyfox.request.RemoveDmxRuleSetting.addRuleSettingId = function(builder, ruleSettingId) {
  builder.addFieldInt32(2, ruleSettingId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.RemoveDmxRuleSetting.endRemoveDmxRuleSetting = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
sisyfox.request.ChangeDmxDeviceSettingValue = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.ChangeDmxDeviceSettingValue}
 */
sisyfox.request.ChangeDmxDeviceSettingValue.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.ChangeDmxDeviceSettingValue=} obj
 * @returns {sisyfox.request.ChangeDmxDeviceSettingValue}
 */
sisyfox.request.ChangeDmxDeviceSettingValue.getRootAsChangeDmxDeviceSettingValue = function(bb, obj) {
  return (obj || new sisyfox.request.ChangeDmxDeviceSettingValue).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
sisyfox.request.ChangeDmxDeviceSettingValue.prototype.deviceId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.ChangeDmxDeviceSettingValue.prototype.settingId = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.ChangeDmxDeviceSettingValue.prototype.value = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readInt8(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.ChangeDmxDeviceSettingValue.startChangeDmxDeviceSettingValue = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} deviceId
 */
sisyfox.request.ChangeDmxDeviceSettingValue.addDeviceId = function(builder, deviceId) {
  builder.addFieldInt32(0, deviceId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} settingId
 */
sisyfox.request.ChangeDmxDeviceSettingValue.addSettingId = function(builder, settingId) {
  builder.addFieldInt32(1, settingId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} value
 */
sisyfox.request.ChangeDmxDeviceSettingValue.addValue = function(builder, value) {
  builder.addFieldInt8(2, value, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.ChangeDmxDeviceSettingValue.endChangeDmxDeviceSettingValue = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
sisyfox.request.SetDmxDeviceMode = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.SetDmxDeviceMode}
 */
sisyfox.request.SetDmxDeviceMode.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.SetDmxDeviceMode=} obj
 * @returns {sisyfox.request.SetDmxDeviceMode}
 */
sisyfox.request.SetDmxDeviceMode.getRootAsSetDmxDeviceMode = function(bb, obj) {
  return (obj || new sisyfox.request.SetDmxDeviceMode).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
sisyfox.request.SetDmxDeviceMode.prototype.deviceId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {sisyfox.request.DmxDeviceMode}
 */
sisyfox.request.SetDmxDeviceMode.prototype.mode = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? /** @type {sisyfox.request.DmxDeviceMode} */ (this.bb.readInt8(this.bb_pos + offset)) : sisyfox.request.DmxDeviceMode.TEST;
};

/**
 * @returns {boolean}
 */
sisyfox.request.SetDmxDeviceMode.prototype.value = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.SetDmxDeviceMode.startSetDmxDeviceMode = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} deviceId
 */
sisyfox.request.SetDmxDeviceMode.addDeviceId = function(builder, deviceId) {
  builder.addFieldInt32(0, deviceId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {sisyfox.request.DmxDeviceMode} mode
 */
sisyfox.request.SetDmxDeviceMode.addMode = function(builder, mode) {
  builder.addFieldInt8(1, mode, sisyfox.request.DmxDeviceMode.TEST);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {boolean} value
 */
sisyfox.request.SetDmxDeviceMode.addValue = function(builder, value) {
  builder.addFieldInt8(2, +value, +false);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.SetDmxDeviceMode.endSetDmxDeviceMode = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
sisyfox.request.GetDmxDevice = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.GetDmxDevice}
 */
sisyfox.request.GetDmxDevice.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.GetDmxDevice=} obj
 * @returns {sisyfox.request.GetDmxDevice}
 */
sisyfox.request.GetDmxDevice.getRootAsGetDmxDevice = function(bb, obj) {
  return (obj || new sisyfox.request.GetDmxDevice).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
sisyfox.request.GetDmxDevice.prototype.deviceId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.GetDmxDevice.startGetDmxDevice = function(builder) {
  builder.startObject(1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} deviceId
 */
sisyfox.request.GetDmxDevice.addDeviceId = function(builder, deviceId) {
  builder.addFieldInt32(0, deviceId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.GetDmxDevice.endGetDmxDevice = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
sisyfox.request.GetDmxDeviceRange = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.GetDmxDeviceRange}
 */
sisyfox.request.GetDmxDeviceRange.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.GetDmxDeviceRange=} obj
 * @returns {sisyfox.request.GetDmxDeviceRange}
 */
sisyfox.request.GetDmxDeviceRange.getRootAsGetDmxDeviceRange = function(bb, obj) {
  return (obj || new sisyfox.request.GetDmxDeviceRange).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
sisyfox.request.GetDmxDeviceRange.prototype.deviceId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.GetDmxDeviceRange.prototype.range = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint8(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.GetDmxDeviceRange.startGetDmxDeviceRange = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} deviceId
 */
sisyfox.request.GetDmxDeviceRange.addDeviceId = function(builder, deviceId) {
  builder.addFieldInt32(0, deviceId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} range
 */
sisyfox.request.GetDmxDeviceRange.addRange = function(builder, range) {
  builder.addFieldInt8(1, range, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.GetDmxDeviceRange.endGetDmxDeviceRange = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
sisyfox.request.GetDmxDeviceChannel = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.GetDmxDeviceChannel}
 */
sisyfox.request.GetDmxDeviceChannel.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.GetDmxDeviceChannel=} obj
 * @returns {sisyfox.request.GetDmxDeviceChannel}
 */
sisyfox.request.GetDmxDeviceChannel.getRootAsGetDmxDeviceChannel = function(bb, obj) {
  return (obj || new sisyfox.request.GetDmxDeviceChannel).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
sisyfox.request.GetDmxDeviceChannel.prototype.deviceId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.GetDmxDeviceChannel.prototype.channelId = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.GetDmxDeviceChannel.startGetDmxDeviceChannel = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} deviceId
 */
sisyfox.request.GetDmxDeviceChannel.addDeviceId = function(builder, deviceId) {
  builder.addFieldInt32(0, deviceId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} channelId
 */
sisyfox.request.GetDmxDeviceChannel.addChannelId = function(builder, channelId) {
  builder.addFieldInt32(1, channelId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.GetDmxDeviceChannel.endGetDmxDeviceChannel = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
sisyfox.request.GetDmxDeviceChannelRange = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.GetDmxDeviceChannelRange}
 */
sisyfox.request.GetDmxDeviceChannelRange.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.GetDmxDeviceChannelRange=} obj
 * @returns {sisyfox.request.GetDmxDeviceChannelRange}
 */
sisyfox.request.GetDmxDeviceChannelRange.getRootAsGetDmxDeviceChannelRange = function(bb, obj) {
  return (obj || new sisyfox.request.GetDmxDeviceChannelRange).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
sisyfox.request.GetDmxDeviceChannelRange.prototype.deviceId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.GetDmxDeviceChannelRange.prototype.channelId = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.GetDmxDeviceChannelRange.prototype.range = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readUint8(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.GetDmxDeviceChannelRange.startGetDmxDeviceChannelRange = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} deviceId
 */
sisyfox.request.GetDmxDeviceChannelRange.addDeviceId = function(builder, deviceId) {
  builder.addFieldInt32(0, deviceId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} channelId
 */
sisyfox.request.GetDmxDeviceChannelRange.addChannelId = function(builder, channelId) {
  builder.addFieldInt32(1, channelId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} range
 */
sisyfox.request.GetDmxDeviceChannelRange.addRange = function(builder, range) {
  builder.addFieldInt8(2, range, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.GetDmxDeviceChannelRange.endGetDmxDeviceChannelRange = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
sisyfox.request.GetDmxChannelRule = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.GetDmxChannelRule}
 */
sisyfox.request.GetDmxChannelRule.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.GetDmxChannelRule=} obj
 * @returns {sisyfox.request.GetDmxChannelRule}
 */
sisyfox.request.GetDmxChannelRule.getRootAsGetDmxChannelRule = function(bb, obj) {
  return (obj || new sisyfox.request.GetDmxChannelRule).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
sisyfox.request.GetDmxChannelRule.prototype.deviceId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.GetDmxChannelRule.prototype.channelId = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.GetDmxChannelRule.prototype.ruleId = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.GetDmxChannelRule.startGetDmxChannelRule = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} deviceId
 */
sisyfox.request.GetDmxChannelRule.addDeviceId = function(builder, deviceId) {
  builder.addFieldInt32(0, deviceId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} channelId
 */
sisyfox.request.GetDmxChannelRule.addChannelId = function(builder, channelId) {
  builder.addFieldInt32(1, channelId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} ruleId
 */
sisyfox.request.GetDmxChannelRule.addRuleId = function(builder, ruleId) {
  builder.addFieldInt32(2, ruleId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.GetDmxChannelRule.endGetDmxChannelRule = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
sisyfox.request.GetDmxChannelRuleRange = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.GetDmxChannelRuleRange}
 */
sisyfox.request.GetDmxChannelRuleRange.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.GetDmxChannelRuleRange=} obj
 * @returns {sisyfox.request.GetDmxChannelRuleRange}
 */
sisyfox.request.GetDmxChannelRuleRange.getRootAsGetDmxChannelRuleRange = function(bb, obj) {
  return (obj || new sisyfox.request.GetDmxChannelRuleRange).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
sisyfox.request.GetDmxChannelRuleRange.prototype.deviceId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.GetDmxChannelRuleRange.prototype.channelId = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.GetDmxChannelRuleRange.prototype.ruleId = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.GetDmxChannelRuleRange.prototype.range = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? this.bb.readUint8(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.GetDmxChannelRuleRange.startGetDmxChannelRuleRange = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} deviceId
 */
sisyfox.request.GetDmxChannelRuleRange.addDeviceId = function(builder, deviceId) {
  builder.addFieldInt32(0, deviceId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} channelId
 */
sisyfox.request.GetDmxChannelRuleRange.addChannelId = function(builder, channelId) {
  builder.addFieldInt32(1, channelId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} ruleId
 */
sisyfox.request.GetDmxChannelRuleRange.addRuleId = function(builder, ruleId) {
  builder.addFieldInt32(2, ruleId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} range
 */
sisyfox.request.GetDmxChannelRuleRange.addRange = function(builder, range) {
  builder.addFieldInt8(3, range, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.GetDmxChannelRuleRange.endGetDmxChannelRuleRange = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
sisyfox.request.GetDmxDeviceSetting = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.GetDmxDeviceSetting}
 */
sisyfox.request.GetDmxDeviceSetting.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.GetDmxDeviceSetting=} obj
 * @returns {sisyfox.request.GetDmxDeviceSetting}
 */
sisyfox.request.GetDmxDeviceSetting.getRootAsGetDmxDeviceSetting = function(bb, obj) {
  return (obj || new sisyfox.request.GetDmxDeviceSetting).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
sisyfox.request.GetDmxDeviceSetting.prototype.deviceId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.GetDmxDeviceSetting.prototype.settingId = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.GetDmxDeviceSetting.startGetDmxDeviceSetting = function(builder) {
  builder.startObject(2);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} deviceId
 */
sisyfox.request.GetDmxDeviceSetting.addDeviceId = function(builder, deviceId) {
  builder.addFieldInt32(0, deviceId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} settingId
 */
sisyfox.request.GetDmxDeviceSetting.addSettingId = function(builder, settingId) {
  builder.addFieldInt32(1, settingId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.GetDmxDeviceSetting.endGetDmxDeviceSetting = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
sisyfox.request.GetDmxDeviceSettingRange = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.GetDmxDeviceSettingRange}
 */
sisyfox.request.GetDmxDeviceSettingRange.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.GetDmxDeviceSettingRange=} obj
 * @returns {sisyfox.request.GetDmxDeviceSettingRange}
 */
sisyfox.request.GetDmxDeviceSettingRange.getRootAsGetDmxDeviceSettingRange = function(bb, obj) {
  return (obj || new sisyfox.request.GetDmxDeviceSettingRange).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
sisyfox.request.GetDmxDeviceSettingRange.prototype.deviceId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.GetDmxDeviceSettingRange.prototype.settingId = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.GetDmxDeviceSettingRange.prototype.range = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readUint8(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.GetDmxDeviceSettingRange.startGetDmxDeviceSettingRange = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} deviceId
 */
sisyfox.request.GetDmxDeviceSettingRange.addDeviceId = function(builder, deviceId) {
  builder.addFieldInt32(0, deviceId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} settingId
 */
sisyfox.request.GetDmxDeviceSettingRange.addSettingId = function(builder, settingId) {
  builder.addFieldInt32(1, settingId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} range
 */
sisyfox.request.GetDmxDeviceSettingRange.addRange = function(builder, range) {
  builder.addFieldInt8(2, range, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.GetDmxDeviceSettingRange.endGetDmxDeviceSettingRange = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
sisyfox.request.GetDmxRuleSetting = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.GetDmxRuleSetting}
 */
sisyfox.request.GetDmxRuleSetting.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.GetDmxRuleSetting=} obj
 * @returns {sisyfox.request.GetDmxRuleSetting}
 */
sisyfox.request.GetDmxRuleSetting.getRootAsGetDmxRuleSetting = function(bb, obj) {
  return (obj || new sisyfox.request.GetDmxRuleSetting).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
sisyfox.request.GetDmxRuleSetting.prototype.deviceId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.GetDmxRuleSetting.prototype.settingId = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.GetDmxRuleSetting.prototype.ruleSettingId = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {sisyfox.request.DmxDeviceSettingType}
 */
sisyfox.request.GetDmxRuleSetting.prototype.type = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? /** @type {sisyfox.request.DmxDeviceSettingType} */ (this.bb.readInt8(this.bb_pos + offset)) : sisyfox.request.DmxDeviceSettingType.RANGE;
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.GetDmxRuleSetting.startGetDmxRuleSetting = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} deviceId
 */
sisyfox.request.GetDmxRuleSetting.addDeviceId = function(builder, deviceId) {
  builder.addFieldInt32(0, deviceId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} settingId
 */
sisyfox.request.GetDmxRuleSetting.addSettingId = function(builder, settingId) {
  builder.addFieldInt32(1, settingId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} ruleSettingId
 */
sisyfox.request.GetDmxRuleSetting.addRuleSettingId = function(builder, ruleSettingId) {
  builder.addFieldInt32(2, ruleSettingId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {sisyfox.request.DmxDeviceSettingType} type
 */
sisyfox.request.GetDmxRuleSetting.addType = function(builder, type) {
  builder.addFieldInt8(3, type, sisyfox.request.DmxDeviceSettingType.RANGE);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.GetDmxRuleSetting.endGetDmxRuleSetting = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
sisyfox.request.GetDmxRuleSettingRange = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {sisyfox.request.GetDmxRuleSettingRange}
 */
sisyfox.request.GetDmxRuleSettingRange.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {sisyfox.request.GetDmxRuleSettingRange=} obj
 * @returns {sisyfox.request.GetDmxRuleSettingRange}
 */
sisyfox.request.GetDmxRuleSettingRange.getRootAsGetDmxRuleSettingRange = function(bb, obj) {
  return (obj || new sisyfox.request.GetDmxRuleSettingRange).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {number}
 */
sisyfox.request.GetDmxRuleSettingRange.prototype.deviceId = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.GetDmxRuleSettingRange.prototype.settingId = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {number}
 */
sisyfox.request.GetDmxRuleSettingRange.prototype.ruleSettingId = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns {sisyfox.request.DmxDeviceSettingType}
 */
sisyfox.request.GetDmxRuleSettingRange.prototype.type = function() {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? /** @type {sisyfox.request.DmxDeviceSettingType} */ (this.bb.readInt8(this.bb_pos + offset)) : sisyfox.request.DmxDeviceSettingType.RANGE;
};

/**
 * @returns {number}
 */
sisyfox.request.GetDmxRuleSettingRange.prototype.range = function() {
  var offset = this.bb.__offset(this.bb_pos, 12);
  return offset ? this.bb.readUint8(this.bb_pos + offset) : 0;
};

/**
 * @param {flatbuffers.Builder} builder
 */
sisyfox.request.GetDmxRuleSettingRange.startGetDmxRuleSettingRange = function(builder) {
  builder.startObject(5);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} deviceId
 */
sisyfox.request.GetDmxRuleSettingRange.addDeviceId = function(builder, deviceId) {
  builder.addFieldInt32(0, deviceId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} settingId
 */
sisyfox.request.GetDmxRuleSettingRange.addSettingId = function(builder, settingId) {
  builder.addFieldInt32(1, settingId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} ruleSettingId
 */
sisyfox.request.GetDmxRuleSettingRange.addRuleSettingId = function(builder, ruleSettingId) {
  builder.addFieldInt32(2, ruleSettingId, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {sisyfox.request.DmxDeviceSettingType} type
 */
sisyfox.request.GetDmxRuleSettingRange.addType = function(builder, type) {
  builder.addFieldInt8(3, type, sisyfox.request.DmxDeviceSettingType.RANGE);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} range
 */
sisyfox.request.GetDmxRuleSettingRange.addRange = function(builder, range) {
  builder.addFieldInt8(4, range, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
sisyfox.request.GetDmxRuleSettingRange.endGetDmxRuleSettingRange = function(builder) {
  var offset = builder.endObject();
  return offset;
};

// Exports for Node.js and RequireJS
this.sisyfox = sisyfox;
