// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol
{

public enum BallSetting : byte
{
 BIG_BALL = 0,
 SMALL_BALL = 1,
};


}
