// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol
{

using global::System;
using global::FlatBuffers;

public struct BoolSetting : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static BoolSetting GetRootAsBoolSetting(ByteBuffer _bb) { return GetRootAsBoolSetting(_bb, new BoolSetting()); }
  public static BoolSetting GetRootAsBoolSetting(ByteBuffer _bb, BoolSetting obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public BoolSetting __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool Value { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<BoolSetting> CreateBoolSetting(FlatBufferBuilder builder,
      bool value = false) {
    builder.StartObject(1);
    BoolSetting.AddValue(builder, value);
    return BoolSetting.EndBoolSetting(builder);
  }

  public static void StartBoolSetting(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddValue(FlatBufferBuilder builder, bool value) { builder.AddBool(0, value, false); }
  public static Offset<BoolSetting> EndBoolSetting(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<BoolSetting>(o);
  }
};


}
