// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol
{

using global::System;
using global::FlatBuffers;

public struct ByteSetting : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ByteSetting GetRootAsByteSetting(ByteBuffer _bb) { return GetRootAsByteSetting(_bb, new ByteSetting()); }
  public static ByteSetting GetRootAsByteSetting(ByteBuffer _bb, ByteSetting obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ByteSetting __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte Value { get { int o = __p.__offset(4); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }

  public static Offset<ByteSetting> CreateByteSetting(FlatBufferBuilder builder,
      byte value = 0) {
    builder.StartObject(1);
    ByteSetting.AddValue(builder, value);
    return ByteSetting.EndByteSetting(builder);
  }

  public static void StartByteSetting(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddValue(FlatBufferBuilder builder, byte value) { builder.AddByte(0, value, 0); }
  public static Offset<ByteSetting> EndByteSetting(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<ByteSetting>(o);
  }
};


}
