// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol
{

public enum Difficulty : byte
{
 VERY_EASY = 0,
 EASY = 1,
 NORMAL = 2,
 HARD = 3,
 VERY_HARD = 4,
};


}
