// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol
{

public enum DmxChannelRuleType : sbyte
{
 GOAL = 0,
 TIME = 1,
 PITCH = 2,
};


}
