// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol
{

public enum DmxDeviceSettingType : sbyte
{
 RANGE = 0,
 CHECKBOX = 1,
};


}
