// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol
{

public enum DmxDeviceMode : sbyte
{
 TEST = 0,
 DISABLED = 1,
};


}
