// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol
{

public enum EndReason : byte
{
 WIN = 0,
 MAP_BORDER = 1,
 COLLISION = 2,
 INSTANT_LOSS_ANGLE = 3,
 GROUND_DIST = 4,
 TOO_STEEP = 5,
 FLASH = 6,
 UNDERWATER = 7,
 TIME_UP = 8,
};


}
