// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol
{

public enum ErrorCode : byte
{
 BAD_TRANSMISSION = 0,
 BAD_VERSION = 1,
 BAD_PAYLOAD_TYPE = 2,
 GENERAL_ERROR = 3,
 NOT_AVAILABLE = 4,
};


}
