// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol
{

public enum ExternalFTDIDevice : sbyte
{
 CCTALK = 0,
 WF700TK = 1,
};


}
