// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol
{

public enum Game : byte
{
 CLASSIC = 0,
 DOWNHILL = 1,
};


}
