// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol
{

public enum GameBlockReason : sbyte
{
 UNKNOWN = 0,
 COIN_ACCEPTOR = 1,
};


}
