// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol
{

public enum GameMode : byte
{
 FREESTYLE = 0,
 LEVEL_COLLECT = 1,
};


}
