// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol
{

public enum GameMode : byte
{
 CLIMB = 0,
 COLLECT = 1,
 EXPLORE = 2,
};


}
