// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol
{

using global::System;
using global::FlatBuffers;

public struct Initials : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Initials __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public sbyte First { get { return __p.bb.GetSbyte(__p.bb_pos + 0); } }
  public sbyte Second { get { return __p.bb.GetSbyte(__p.bb_pos + 1); } }
  public sbyte Third { get { return __p.bb.GetSbyte(__p.bb_pos + 2); } }

  public static Offset<Initials> CreateInitials(FlatBufferBuilder builder, sbyte First, sbyte Second, sbyte Third) {
    builder.Prep(1, 3);
    builder.PutSbyte(Third);
    builder.PutSbyte(Second);
    builder.PutSbyte(First);
    return new Offset<Initials>(builder.Offset);
  }
};


}
