// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol
{

using global::System;
using global::FlatBuffers;

public struct IntSetting : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static IntSetting GetRootAsIntSetting(ByteBuffer _bb) { return GetRootAsIntSetting(_bb, new IntSetting()); }
  public static IntSetting GetRootAsIntSetting(ByteBuffer _bb, IntSetting obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public IntSetting __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Value { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<IntSetting> CreateIntSetting(FlatBufferBuilder builder,
      uint value = 0) {
    builder.StartObject(1);
    IntSetting.AddValue(builder, value);
    return IntSetting.EndIntSetting(builder);
  }

  public static void StartIntSetting(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddValue(FlatBufferBuilder builder, uint value) { builder.AddUint(0, value, 0); }
  public static Offset<IntSetting> EndIntSetting(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<IntSetting>(o);
  }
};


}
