// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol
{

public enum Language : byte
{
 ENGLISH = 0,
 GERMAN = 1,
 CRUMMY_GERMAN = 255,
};


}
