// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol
{

using global::System;
using global::FlatBuffers;

public struct LiveData : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public LiveData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Height { get { return __p.bb.GetInt(__p.bb_pos + 0); } }
  public int Time { get { return __p.bb.GetInt(__p.bb_pos + 4); } }
  public int Pitch { get { return __p.bb.GetInt(__p.bb_pos + 8); } }

  public static Offset<LiveData> CreateLiveData(FlatBufferBuilder builder, int Height, int Time, int Pitch) {
    builder.Prep(4, 12);
    builder.PutInt(Pitch);
    builder.PutInt(Time);
    builder.PutInt(Height);
    return new Offset<LiveData>(builder.Offset);
  }
};


}
