// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol
{

public enum Payload : byte
{
 NONE = 0,
 Error = 1,
 Info = 2,
 AddScore = 3,
 GetScore = 4,
 GetScoreRange = 5,
 SetLiveData = 6,
 GetLiveData = 7,
 AddUser = 8,
 GetUser = 9,
 SetUser = 10,
 GetCurrentUser = 11,
 GetUserRange = 12,
 RemoveUser = 13,
 UnsetUser = 14,
 AddLocation = 15,
 GetLocation = 16,
 SetSetting = 17,
 GetSetting = 18,
 GetSettings = 19,
 Trigger = 20,
 AddDmxDevice = 21,
 RemoveDmxDevice = 22,
 AddDmxDeviceChannel = 23,
 RemoveDmxDeviceChannel = 24,
 AddDmxChannelRule = 25,
 RemoveDmxChannelRule = 26,
 AddDmxDeviceSetting = 27,
 RemoveDmxDeviceSetting = 28,
 AddDmxRuleRangeSetting = 29,
 AddDmxRuleBoolSetting = 30,
 RemoveDmxRuleSetting = 31,
 ChangeDmxDeviceSettingValue = 32,
 GetDmxDevice = 33,
 GetDmxDeviceChannel = 34,
 GetDmxChannelRule = 35,
 GetDmxDeviceSetting = 36,
 GetDmxRuleSetting = 37,
 GetDmxDeviceRange = 38,
 GetDmxDeviceChannelRange = 39,
 GetDmxChannelRuleRange = 40,
 GetDmxDeviceSettingRange = 41,
 GetDmxRuleSettingRange = 42,
 SetDmxDeviceMode = 43,
};


}
