// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol
{

public enum PayPerPlayMode : sbyte
{
 COIN = 0,
 TOKEN = 1,
};


}
