// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol
{

public enum Sensor : byte
{
 V1_0 = 0,
 V1_1 = 1,
 V2_0 = 2,
};


}
