// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol
{

public enum SettingType : byte
{
 GAME_LANGUAGE = 0,
 INTERFACE_LANGUAGE = 1,
 MASTER_VOLUME = 2,
 COMPETITION_MODE = 3,
 DEBUG_MODE = 4,
 TIMEFRAME = 5,
 MUSIC_VOLUME = 6,
 SFX_VOLUME = 7,
 VOICES = 8,
 IDLE_TIME = 9,
 WIN_TRANSITIONS_TO_LOSS = 10,
 BALL_SETTING = 11,
 PLAY_VIDEO = 12,
 VIDEO_DELAY = 13,
 VIDEO_SELECTION = 14,
 INGAME_MENU = 15,
 SENSOR = 16,
 SF_CONTROL_INTERNAL = 63,
 WORLD = 64,
 LEVEL = 65,
 DIFFICULTY = 66,
 GAME_MODE = 67,
 MAX_COLLECT_WORLD = 68,
 MAX_COLLECT_LEVEL = 69,
 GEM_SCORE = 70,
 TIME_ATTACK = 71,
 RESERVED_FOR_FUTURE_USE_1 = 72,
 HASH = 73,
 GAME = 74,
 GAME_ACTIVE = 128,
 GAME_ENABLED = 129,
};


}
