// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol
{

public enum SettingValue : byte
{
 NONE = 0,
 SimpleValue = 1,
 Hash = 2,
};


}
