// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol
{

public enum SettingType : byte
{
 GAME_LANGUAGE = 0,
 INTERFACE_LANGUAGE = 1,
 SOUND_LEVEL = 2,
 COMPETITION_MODE = 3,
 DEBUG_MODE = 4,
 WORLD = 64,
 LEVEL = 65,
 DIFFICULTY = 66,
 GAME_MODE = 67,
 MAX_COLLECT_WORLD = 68,
 MAX_COLLECT_LEVEL = 69,
 GEM_SCORE = 70,
 GAME_ACTIVE = 128,
 GAME_ENABLED = 129,
};


}
