// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol
{

using global::System;
using global::FlatBuffers;

public struct Setting : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Setting __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public SettingType Type { get { return (SettingType)__p.bb.Get(__p.bb_pos + 0); } }
  public uint Value { get { return __p.bb.GetUint(__p.bb_pos + 4); } }

  public static Offset<Setting> CreateSetting(FlatBufferBuilder builder, SettingType Type, uint Value) {
    builder.Prep(4, 8);
    builder.PutUint(Value);
    builder.Pad(3);
    builder.PutByte((byte)Type);
    return new Offset<Setting>(builder.Offset);
  }
};


}
