// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol
{

using global::System;
using global::FlatBuffers;

public struct Setting : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Setting GetRootAsSetting(ByteBuffer _bb) { return GetRootAsSetting(_bb, new Setting()); }
  public static Setting GetRootAsSetting(ByteBuffer _bb, Setting obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Setting __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public SettingType Type { get { int o = __p.__offset(4); return o != 0 ? (SettingType)__p.bb.Get(o + __p.bb_pos) : SettingType.GAME_LANGUAGE; } }
  public SettingValue ValueType { get { int o = __p.__offset(6); return o != 0 ? (SettingValue)__p.bb.Get(o + __p.bb_pos) : SettingValue.NONE; } }
  public TTable? Value<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(8); return o != 0 ? (TTable?)__p.__union<TTable>(o) : null; }

  public static Offset<Setting> CreateSetting(FlatBufferBuilder builder,
      SettingType type = SettingType.GAME_LANGUAGE,
      SettingValue value_type = SettingValue.NONE,
      int valueOffset = 0) {
    builder.StartObject(3);
    Setting.AddValue(builder, valueOffset);
    Setting.AddValueType(builder, value_type);
    Setting.AddType(builder, type);
    return Setting.EndSetting(builder);
  }

  public static void StartSetting(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddType(FlatBufferBuilder builder, SettingType type) { builder.AddByte(0, (byte)type, 0); }
  public static void AddValueType(FlatBufferBuilder builder, SettingValue valueType) { builder.AddByte(1, (byte)valueType, 0); }
  public static void AddValue(FlatBufferBuilder builder, int valueOffset) { builder.AddOffset(2, valueOffset, 0); }
  public static Offset<Setting> EndSetting(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Setting>(o);
  }
};


}
