// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol
{

public enum SettingValue : byte
{
 NONE = 0,
 BoolSetting = 1,
 ByteSetting = 2,
 IntSetting = 3,
 Hash = 4,
};


}
