// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol
{

public enum SettingVariableType : byte
{
 BOOL = 0,
 UBYTE = 1,
 UINT = 2,
};


}
