// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol
{

public enum TimeFrame : sbyte
{
 HOURLY = 0,
 DAILY = 1,
 WEEKLY = 2,
 MONTHLY = 3,
};


}
