// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol
{

using global::System;
using global::FlatBuffers;

public struct UserSetting : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public UserSetting __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool Available { get { return 0!=__p.bb.Get(__p.bb_pos + 0); } }
  public World World { get { return (World)__p.bb.Get(__p.bb_pos + 1); } }
  public byte Level { get { return __p.bb.Get(__p.bb_pos + 2); } }
  public byte Difficulty { get { return __p.bb.Get(__p.bb_pos + 3); } }
  public byte GameMode { get { return __p.bb.Get(__p.bb_pos + 4); } }
  public uint GemScore { get { return __p.bb.GetUint(__p.bb_pos + 8); } }
  public byte MaxCollectWorld { get { return __p.bb.Get(__p.bb_pos + 12); } }
  public byte MaxCollectLevel { get { return __p.bb.Get(__p.bb_pos + 13); } }

  public static Offset<UserSetting> CreateUserSetting(FlatBufferBuilder builder, bool Available, World World, byte Level, byte Difficulty, byte GameMode, uint GemScore, byte MaxCollectWorld, byte MaxCollectLevel) {
    builder.Prep(4, 16);
    builder.Pad(2);
    builder.PutByte(MaxCollectLevel);
    builder.PutByte(MaxCollectWorld);
    builder.PutUint(GemScore);
    builder.Pad(3);
    builder.PutByte(GameMode);
    builder.PutByte(Difficulty);
    builder.PutByte(Level);
    builder.PutByte((byte)World);
    builder.PutBool(Available);
    return new Offset<UserSetting>(builder.Offset);
  }
};


}
