// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol
{

using global::System;
using global::FlatBuffers;

public struct User : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static User GetRootAsUser(ByteBuffer _bb) { return GetRootAsUser(_bb, new User()); }
  public static User GetRootAsUser(ByteBuffer _bb, User obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public User __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint UId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public ulong Timestamp { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public string Name { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(8); }
  public string Info { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetInfoBytes() { return __p.__vector_as_arraysegment(10); }

  public static Offset<User> CreateUser(FlatBufferBuilder builder,
      uint uId = 0,
      ulong timestamp = 0,
      StringOffset nameOffset = default(StringOffset),
      StringOffset infoOffset = default(StringOffset)) {
    builder.StartObject(4);
    User.AddTimestamp(builder, timestamp);
    User.AddInfo(builder, infoOffset);
    User.AddName(builder, nameOffset);
    User.AddUId(builder, uId);
    return User.EndUser(builder);
  }

  public static void StartUser(FlatBufferBuilder builder) { builder.StartObject(4); }
  public static void AddUId(FlatBufferBuilder builder, uint uId) { builder.AddUint(0, uId, 0); }
  public static void AddTimestamp(FlatBufferBuilder builder, ulong timestamp) { builder.AddUlong(1, timestamp, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(2, nameOffset.Value, 0); }
  public static void AddInfo(FlatBufferBuilder builder, StringOffset infoOffset) { builder.AddOffset(3, infoOffset.Value, 0); }
  public static Offset<User> EndUser(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<User>(o);
  }
};


}
