// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol
{

using global::System;
using global::FlatBuffers;

public struct Version : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Version __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte High { get { return __p.bb.Get(__p.bb_pos + 0); } }
  public byte Low { get { return __p.bb.Get(__p.bb_pos + 1); } }

  public static Offset<Version> CreateVersion(FlatBufferBuilder builder, byte High, byte Low) {
    builder.Prep(1, 2);
    builder.PutByte(Low);
    builder.PutByte(High);
    return new Offset<Version>(builder.Offset);
  }
};


}
