// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol
{

public enum VideoSelection : byte
{
 DEFAULT = 0,
 PRODUCT = 1,
 CUSTOMER = 2,
};


}
