// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol
{

public enum World : byte
{
 ORIGIN_MOUNTAIN = 0,
 BLOCKSBERG = 1,
 RED_CANYON = 2,
 SECRET_ISLAND = 3,
 TUTORIAL = 4,
};


}
