// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.request
{

using global::System;
using global::FlatBuffers;

public struct AccountStatus : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static AccountStatus GetRootAsAccountStatus(ByteBuffer _bb) { return GetRootAsAccountStatus(_bb, new AccountStatus()); }
  public static AccountStatus GetRootAsAccountStatus(ByteBuffer _bb, AccountStatus obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public AccountStatus __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartAccountStatus(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<AccountStatus> EndAccountStatus(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<AccountStatus>(o);
  }
};


}
