// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.request
{

using global::System;
using global::FlatBuffers;

public struct AddDmxChannelRule : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static AddDmxChannelRule GetRootAsAddDmxChannelRule(ByteBuffer _bb) { return GetRootAsAddDmxChannelRule(_bb, new AddDmxChannelRule()); }
  public static AddDmxChannelRule GetRootAsAddDmxChannelRule(ByteBuffer _bb, AddDmxChannelRule obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public AddDmxChannelRule __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint DeviceId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint ChannelId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public sisyfox.sisycol.DmxChannelRuleType RuleType { get { int o = __p.__offset(8); return o != 0 ? (sisyfox.sisycol.DmxChannelRuleType)__p.bb.GetSbyte(o + __p.bb_pos) : sisyfox.sisycol.DmxChannelRuleType.HEIGHT; } }
  public int On { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Off { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public byte Start { get { int o = __p.__offset(14); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public float Step { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<AddDmxChannelRule> CreateAddDmxChannelRule(FlatBufferBuilder builder,
      uint deviceId = 0,
      uint channelId = 0,
      sisyfox.sisycol.DmxChannelRuleType ruleType = sisyfox.sisycol.DmxChannelRuleType.HEIGHT,
      int on = 0,
      int off = 0,
      byte start = 0,
      float step = 0.0f) {
    builder.StartObject(7);
    AddDmxChannelRule.AddStep(builder, step);
    AddDmxChannelRule.AddOff(builder, off);
    AddDmxChannelRule.AddOn(builder, on);
    AddDmxChannelRule.AddChannelId(builder, channelId);
    AddDmxChannelRule.AddDeviceId(builder, deviceId);
    AddDmxChannelRule.AddStart(builder, start);
    AddDmxChannelRule.AddRuleType(builder, ruleType);
    return AddDmxChannelRule.EndAddDmxChannelRule(builder);
  }

  public static void StartAddDmxChannelRule(FlatBufferBuilder builder) { builder.StartObject(7); }
  public static void AddDeviceId(FlatBufferBuilder builder, uint deviceId) { builder.AddUint(0, deviceId, 0); }
  public static void AddChannelId(FlatBufferBuilder builder, uint channelId) { builder.AddUint(1, channelId, 0); }
  public static void AddRuleType(FlatBufferBuilder builder, sisyfox.sisycol.DmxChannelRuleType ruleType) { builder.AddSbyte(2, (sbyte)ruleType, 0); }
  public static void AddOn(FlatBufferBuilder builder, int on) { builder.AddInt(3, on, 0); }
  public static void AddOff(FlatBufferBuilder builder, int off) { builder.AddInt(4, off, 0); }
  public static void AddStart(FlatBufferBuilder builder, byte start) { builder.AddByte(5, start, 0); }
  public static void AddStep(FlatBufferBuilder builder, float step) { builder.AddFloat(6, step, 0.0f); }
  public static Offset<AddDmxChannelRule> EndAddDmxChannelRule(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<AddDmxChannelRule>(o);
  }
};


}
