// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.request
{

using global::System;
using global::FlatBuffers;

public struct AddDmxDevice : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static AddDmxDevice GetRootAsAddDmxDevice(ByteBuffer _bb) { return GetRootAsAddDmxDevice(_bb, new AddDmxDevice()); }
  public static AddDmxDevice GetRootAsAddDmxDevice(ByteBuffer _bb, AddDmxDevice obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public AddDmxDevice __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }

  public static Offset<AddDmxDevice> CreateAddDmxDevice(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset)) {
    builder.StartObject(1);
    AddDmxDevice.AddName(builder, nameOffset);
    return AddDmxDevice.EndAddDmxDevice(builder);
  }

  public static void StartAddDmxDevice(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static Offset<AddDmxDevice> EndAddDmxDevice(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<AddDmxDevice>(o);
  }
};


}
