// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.request
{

using global::System;
using global::FlatBuffers;

public struct AddDmxDeviceSetting : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static AddDmxDeviceSetting GetRootAsAddDmxDeviceSetting(ByteBuffer _bb) { return GetRootAsAddDmxDeviceSetting(_bb, new AddDmxDeviceSetting()); }
  public static AddDmxDeviceSetting GetRootAsAddDmxDeviceSetting(ByteBuffer _bb, AddDmxDeviceSetting obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public AddDmxDeviceSetting __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint DeviceId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public sisyfox.sisycol.DmxDeviceSettingType SettingType { get { int o = __p.__offset(6); return o != 0 ? (sisyfox.sisycol.DmxDeviceSettingType)__p.bb.GetSbyte(o + __p.bb_pos) : sisyfox.sisycol.DmxDeviceSettingType.RANGE; } }
  public string Name { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(8); }
  public sbyte Norm { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetSbyte(o + __p.bb_pos) : (sbyte)0; } }

  public static Offset<AddDmxDeviceSetting> CreateAddDmxDeviceSetting(FlatBufferBuilder builder,
      uint deviceId = 0,
      sisyfox.sisycol.DmxDeviceSettingType settingType = sisyfox.sisycol.DmxDeviceSettingType.RANGE,
      StringOffset nameOffset = default(StringOffset),
      sbyte norm = 0) {
    builder.StartObject(4);
    AddDmxDeviceSetting.AddName(builder, nameOffset);
    AddDmxDeviceSetting.AddDeviceId(builder, deviceId);
    AddDmxDeviceSetting.AddNorm(builder, norm);
    AddDmxDeviceSetting.AddSettingType(builder, settingType);
    return AddDmxDeviceSetting.EndAddDmxDeviceSetting(builder);
  }

  public static void StartAddDmxDeviceSetting(FlatBufferBuilder builder) { builder.StartObject(4); }
  public static void AddDeviceId(FlatBufferBuilder builder, uint deviceId) { builder.AddUint(0, deviceId, 0); }
  public static void AddSettingType(FlatBufferBuilder builder, sisyfox.sisycol.DmxDeviceSettingType settingType) { builder.AddSbyte(1, (sbyte)settingType, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(2, nameOffset.Value, 0); }
  public static void AddNorm(FlatBufferBuilder builder, sbyte norm) { builder.AddSbyte(3, norm, 0); }
  public static Offset<AddDmxDeviceSetting> EndAddDmxDeviceSetting(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<AddDmxDeviceSetting>(o);
  }
};


}
