// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.request
{

using global::System;
using global::FlatBuffers;

public struct AddLocation : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static AddLocation GetRootAsAddLocation(ByteBuffer _bb) { return GetRootAsAddLocation(_bb, new AddLocation()); }
  public static AddLocation GetRootAsAddLocation(ByteBuffer _bb, AddLocation obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public AddLocation __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint StartId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }

  public static Offset<AddLocation> CreateAddLocation(FlatBufferBuilder builder,
      uint startId = 0,
      StringOffset nameOffset = default(StringOffset)) {
    builder.StartObject(2);
    AddLocation.AddName(builder, nameOffset);
    AddLocation.AddStartId(builder, startId);
    return AddLocation.EndAddLocation(builder);
  }

  public static void StartAddLocation(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddStartId(FlatBufferBuilder builder, uint startId) { builder.AddUint(0, startId, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(1, nameOffset.Value, 0); }
  public static Offset<AddLocation> EndAddLocation(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<AddLocation>(o);
  }
};


}
