// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.request
{

using global::System;
using global::FlatBuffers;

public struct AddScoreNew : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static AddScoreNew GetRootAsAddScoreNew(ByteBuffer _bb) { return GetRootAsAddScoreNew(_bb, new AddScoreNew()); }
  public static AddScoreNew GetRootAsAddScoreNew(ByteBuffer _bb, AddScoreNew obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public AddScoreNew __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public sisyfox.sisycol.Score? Data { get { int o = __p.__offset(4); return o != 0 ? (sisyfox.sisycol.Score?)(new sisyfox.sisycol.Score()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<AddScoreNew> CreateAddScoreNew(FlatBufferBuilder builder,
      Offset<sisyfox.sisycol.Score> dataOffset = default(Offset<sisyfox.sisycol.Score>)) {
    builder.StartObject(1);
    AddScoreNew.AddData(builder, dataOffset);
    return AddScoreNew.EndAddScoreNew(builder);
  }

  public static void StartAddScoreNew(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddData(FlatBufferBuilder builder, Offset<sisyfox.sisycol.Score> dataOffset) { builder.AddOffset(0, dataOffset.Value, 0); }
  public static Offset<AddScoreNew> EndAddScoreNew(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<AddScoreNew>(o);
  }
};


}
