// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.request
{

using global::System;
using global::FlatBuffers;

public struct GetCurrentUser : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static GetCurrentUser GetRootAsGetCurrentUser(ByteBuffer _bb) { return GetRootAsGetCurrentUser(_bb, new GetCurrentUser()); }
  public static GetCurrentUser GetRootAsGetCurrentUser(ByteBuffer _bb, GetCurrentUser obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public GetCurrentUser __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartGetCurrentUser(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<GetCurrentUser> EndGetCurrentUser(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GetCurrentUser>(o);
  }
};


}
