// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.request
{

using global::System;
using global::FlatBuffers;

public struct GetDetectedDevices : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static GetDetectedDevices GetRootAsGetDetectedDevices(ByteBuffer _bb) { return GetRootAsGetDetectedDevices(_bb, new GetDetectedDevices()); }
  public static GetDetectedDevices GetRootAsGetDetectedDevices(ByteBuffer _bb, GetDetectedDevices obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public GetDetectedDevices __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartGetDetectedDevices(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<GetDetectedDevices> EndGetDetectedDevices(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GetDetectedDevices>(o);
  }
};


}
