// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.request
{

using global::System;
using global::FlatBuffers;

public struct GetDmxDevice : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static GetDmxDevice GetRootAsGetDmxDevice(ByteBuffer _bb) { return GetRootAsGetDmxDevice(_bb, new GetDmxDevice()); }
  public static GetDmxDevice GetRootAsGetDmxDevice(ByteBuffer _bb, GetDmxDevice obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public GetDmxDevice __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint DeviceId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<GetDmxDevice> CreateGetDmxDevice(FlatBufferBuilder builder,
      uint deviceId = 0) {
    builder.StartObject(1);
    GetDmxDevice.AddDeviceId(builder, deviceId);
    return GetDmxDevice.EndGetDmxDevice(builder);
  }

  public static void StartGetDmxDevice(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddDeviceId(FlatBufferBuilder builder, uint deviceId) { builder.AddUint(0, deviceId, 0); }
  public static Offset<GetDmxDevice> EndGetDmxDevice(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GetDmxDevice>(o);
  }
};


}
