// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.request
{

using global::System;
using global::FlatBuffers;

public struct GetDmxRuleSettingRange : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static GetDmxRuleSettingRange GetRootAsGetDmxRuleSettingRange(ByteBuffer _bb) { return GetRootAsGetDmxRuleSettingRange(_bb, new GetDmxRuleSettingRange()); }
  public static GetDmxRuleSettingRange GetRootAsGetDmxRuleSettingRange(ByteBuffer _bb, GetDmxRuleSettingRange obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public GetDmxRuleSettingRange __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint DeviceId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint SettingId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint RuleSettingId { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public sisyfox.sisycol.DmxDeviceSettingType Type { get { int o = __p.__offset(10); return o != 0 ? (sisyfox.sisycol.DmxDeviceSettingType)__p.bb.GetSbyte(o + __p.bb_pos) : sisyfox.sisycol.DmxDeviceSettingType.RANGE; } }
  public byte Range { get { int o = __p.__offset(12); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }

  public static Offset<GetDmxRuleSettingRange> CreateGetDmxRuleSettingRange(FlatBufferBuilder builder,
      uint deviceId = 0,
      uint settingId = 0,
      uint ruleSettingId = 0,
      sisyfox.sisycol.DmxDeviceSettingType type = sisyfox.sisycol.DmxDeviceSettingType.RANGE,
      byte range = 0) {
    builder.StartObject(5);
    GetDmxRuleSettingRange.AddRuleSettingId(builder, ruleSettingId);
    GetDmxRuleSettingRange.AddSettingId(builder, settingId);
    GetDmxRuleSettingRange.AddDeviceId(builder, deviceId);
    GetDmxRuleSettingRange.AddRange(builder, range);
    GetDmxRuleSettingRange.AddType(builder, type);
    return GetDmxRuleSettingRange.EndGetDmxRuleSettingRange(builder);
  }

  public static void StartGetDmxRuleSettingRange(FlatBufferBuilder builder) { builder.StartObject(5); }
  public static void AddDeviceId(FlatBufferBuilder builder, uint deviceId) { builder.AddUint(0, deviceId, 0); }
  public static void AddSettingId(FlatBufferBuilder builder, uint settingId) { builder.AddUint(1, settingId, 0); }
  public static void AddRuleSettingId(FlatBufferBuilder builder, uint ruleSettingId) { builder.AddUint(2, ruleSettingId, 0); }
  public static void AddType(FlatBufferBuilder builder, sisyfox.sisycol.DmxDeviceSettingType type) { builder.AddSbyte(3, (sbyte)type, 0); }
  public static void AddRange(FlatBufferBuilder builder, byte range) { builder.AddByte(4, range, 0); }
  public static Offset<GetDmxRuleSettingRange> EndGetDmxRuleSettingRange(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GetDmxRuleSettingRange>(o);
  }
};


}
