// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.request
{

using global::System;
using global::FlatBuffers;

public struct GetDmxDeviceSettingRange : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static GetDmxDeviceSettingRange GetRootAsGetDmxDeviceSettingRange(ByteBuffer _bb) { return GetRootAsGetDmxDeviceSettingRange(_bb, new GetDmxDeviceSettingRange()); }
  public static GetDmxDeviceSettingRange GetRootAsGetDmxDeviceSettingRange(ByteBuffer _bb, GetDmxDeviceSettingRange obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public GetDmxDeviceSettingRange __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint DeviceId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint SettingId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public byte Range { get { int o = __p.__offset(8); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }

  public static Offset<GetDmxDeviceSettingRange> CreateGetDmxDeviceSettingRange(FlatBufferBuilder builder,
      uint deviceId = 0,
      uint settingId = 0,
      byte range = 0) {
    builder.StartObject(3);
    GetDmxDeviceSettingRange.AddSettingId(builder, settingId);
    GetDmxDeviceSettingRange.AddDeviceId(builder, deviceId);
    GetDmxDeviceSettingRange.AddRange(builder, range);
    return GetDmxDeviceSettingRange.EndGetDmxDeviceSettingRange(builder);
  }

  public static void StartGetDmxDeviceSettingRange(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddDeviceId(FlatBufferBuilder builder, uint deviceId) { builder.AddUint(0, deviceId, 0); }
  public static void AddSettingId(FlatBufferBuilder builder, uint settingId) { builder.AddUint(1, settingId, 0); }
  public static void AddRange(FlatBufferBuilder builder, byte range) { builder.AddByte(2, range, 0); }
  public static Offset<GetDmxDeviceSettingRange> EndGetDmxDeviceSettingRange(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GetDmxDeviceSettingRange>(o);
  }
};


}
