// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.request
{

using global::System;
using global::FlatBuffers;

public struct GetDmxDeviceRange : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static GetDmxDeviceRange GetRootAsGetDmxDeviceRange(ByteBuffer _bb) { return GetRootAsGetDmxDeviceRange(_bb, new GetDmxDeviceRange()); }
  public static GetDmxDeviceRange GetRootAsGetDmxDeviceRange(ByteBuffer _bb, GetDmxDeviceRange obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public GetDmxDeviceRange __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint DeviceId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public byte Range { get { int o = __p.__offset(6); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }

  public static Offset<GetDmxDeviceRange> CreateGetDmxDeviceRange(FlatBufferBuilder builder,
      uint deviceId = 0,
      byte range = 0) {
    builder.StartObject(2);
    GetDmxDeviceRange.AddDeviceId(builder, deviceId);
    GetDmxDeviceRange.AddRange(builder, range);
    return GetDmxDeviceRange.EndGetDmxDeviceRange(builder);
  }

  public static void StartGetDmxDeviceRange(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddDeviceId(FlatBufferBuilder builder, uint deviceId) { builder.AddUint(0, deviceId, 0); }
  public static void AddRange(FlatBufferBuilder builder, byte range) { builder.AddByte(1, range, 0); }
  public static Offset<GetDmxDeviceRange> EndGetDmxDeviceRange(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GetDmxDeviceRange>(o);
  }
};


}
