// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.request
{

using global::System;
using global::FlatBuffers;

public struct GetIdealTime_DEPRECATED : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static GetIdealTime_DEPRECATED GetRootAsGetIdealTime_DEPRECATED(ByteBuffer _bb) { return GetRootAsGetIdealTime_DEPRECATED(_bb, new GetIdealTime_DEPRECATED()); }
  public static GetIdealTime_DEPRECATED GetRootAsGetIdealTime_DEPRECATED(ByteBuffer _bb, GetIdealTime_DEPRECATED obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public GetIdealTime_DEPRECATED __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartGetIdealTime_DEPRECATED(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<GetIdealTime_DEPRECATED> EndGetIdealTime_DEPRECATED(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GetIdealTime_DEPRECATED>(o);
  }
};


}
