// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.request
{

using global::System;
using global::FlatBuffers;

public struct GetRemoteDevices : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static GetRemoteDevices GetRootAsGetRemoteDevices(ByteBuffer _bb) { return GetRootAsGetRemoteDevices(_bb, new GetRemoteDevices()); }
  public static GetRemoteDevices GetRootAsGetRemoteDevices(ByteBuffer _bb, GetRemoteDevices obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public GetRemoteDevices __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartGetRemoteDevices(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<GetRemoteDevices> EndGetRemoteDevices(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GetRemoteDevices>(o);
  }
};


}
