// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.request
{

using global::System;
using global::FlatBuffers;

public struct GetSettings : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static GetSettings GetRootAsGetSettings(ByteBuffer _bb) { return GetRootAsGetSettings(_bb, new GetSettings()); }
  public static GetSettings GetRootAsGetSettings(ByteBuffer _bb, GetSettings obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public GetSettings __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartGetSettings(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<GetSettings> EndGetSettings(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GetSettings>(o);
  }
};


}
