// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.request
{

using global::System;
using global::FlatBuffers;

public struct RemoveUser : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static RemoveUser GetRootAsRemoveUser(ByteBuffer _bb) { return GetRootAsRemoveUser(_bb, new RemoveUser()); }
  public static RemoveUser GetRootAsRemoveUser(ByteBuffer _bb, RemoveUser obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public RemoveUser __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Uid { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<RemoveUser> CreateRemoveUser(FlatBufferBuilder builder,
      uint uid = 0) {
    builder.StartObject(1);
    RemoveUser.AddUid(builder, uid);
    return RemoveUser.EndRemoveUser(builder);
  }

  public static void StartRemoveUser(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddUid(FlatBufferBuilder builder, uint uid) { builder.AddUint(0, uid, 0); }
  public static Offset<RemoveUser> EndRemoveUser(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<RemoveUser>(o);
  }
};


}
