// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.request
{

using global::System;
using global::FlatBuffers;

public struct RemoveDmxDeviceChannel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static RemoveDmxDeviceChannel GetRootAsRemoveDmxDeviceChannel(ByteBuffer _bb) { return GetRootAsRemoveDmxDeviceChannel(_bb, new RemoveDmxDeviceChannel()); }
  public static RemoveDmxDeviceChannel GetRootAsRemoveDmxDeviceChannel(ByteBuffer _bb, RemoveDmxDeviceChannel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public RemoveDmxDeviceChannel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint DeviceId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint ChannelId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<RemoveDmxDeviceChannel> CreateRemoveDmxDeviceChannel(FlatBufferBuilder builder,
      uint deviceId = 0,
      uint channelId = 0) {
    builder.StartObject(2);
    RemoveDmxDeviceChannel.AddChannelId(builder, channelId);
    RemoveDmxDeviceChannel.AddDeviceId(builder, deviceId);
    return RemoveDmxDeviceChannel.EndRemoveDmxDeviceChannel(builder);
  }

  public static void StartRemoveDmxDeviceChannel(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddDeviceId(FlatBufferBuilder builder, uint deviceId) { builder.AddUint(0, deviceId, 0); }
  public static void AddChannelId(FlatBufferBuilder builder, uint channelId) { builder.AddUint(1, channelId, 0); }
  public static Offset<RemoveDmxDeviceChannel> EndRemoveDmxDeviceChannel(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<RemoveDmxDeviceChannel>(o);
  }
};


}
