// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.request
{

using global::System;
using global::FlatBuffers;

public struct SetCoinAcceptorMode : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static SetCoinAcceptorMode GetRootAsSetCoinAcceptorMode(ByteBuffer _bb) { return GetRootAsSetCoinAcceptorMode(_bb, new SetCoinAcceptorMode()); }
  public static SetCoinAcceptorMode GetRootAsSetCoinAcceptorMode(ByteBuffer _bb, SetCoinAcceptorMode obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public SetCoinAcceptorMode __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool EnableInput { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<SetCoinAcceptorMode> CreateSetCoinAcceptorMode(FlatBufferBuilder builder,
      bool enableInput = false) {
    builder.StartObject(1);
    SetCoinAcceptorMode.AddEnableInput(builder, enableInput);
    return SetCoinAcceptorMode.EndSetCoinAcceptorMode(builder);
  }

  public static void StartSetCoinAcceptorMode(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddEnableInput(FlatBufferBuilder builder, bool enableInput) { builder.AddBool(0, enableInput, false); }
  public static Offset<SetCoinAcceptorMode> EndSetCoinAcceptorMode(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<SetCoinAcceptorMode>(o);
  }
};


}
