// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.request
{

using global::System;
using global::FlatBuffers;

public struct SetDmxDeviceMode : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static SetDmxDeviceMode GetRootAsSetDmxDeviceMode(ByteBuffer _bb) { return GetRootAsSetDmxDeviceMode(_bb, new SetDmxDeviceMode()); }
  public static SetDmxDeviceMode GetRootAsSetDmxDeviceMode(ByteBuffer _bb, SetDmxDeviceMode obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public SetDmxDeviceMode __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint DeviceId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public sisyfox.sisycol.DmxDeviceMode Mode { get { int o = __p.__offset(6); return o != 0 ? (sisyfox.sisycol.DmxDeviceMode)__p.bb.GetSbyte(o + __p.bb_pos) : sisyfox.sisycol.DmxDeviceMode.TEST; } }
  public bool Value { get { int o = __p.__offset(8); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<SetDmxDeviceMode> CreateSetDmxDeviceMode(FlatBufferBuilder builder,
      uint deviceId = 0,
      sisyfox.sisycol.DmxDeviceMode mode = sisyfox.sisycol.DmxDeviceMode.TEST,
      bool value = false) {
    builder.StartObject(3);
    SetDmxDeviceMode.AddDeviceId(builder, deviceId);
    SetDmxDeviceMode.AddValue(builder, value);
    SetDmxDeviceMode.AddMode(builder, mode);
    return SetDmxDeviceMode.EndSetDmxDeviceMode(builder);
  }

  public static void StartSetDmxDeviceMode(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddDeviceId(FlatBufferBuilder builder, uint deviceId) { builder.AddUint(0, deviceId, 0); }
  public static void AddMode(FlatBufferBuilder builder, sisyfox.sisycol.DmxDeviceMode mode) { builder.AddSbyte(1, (sbyte)mode, 0); }
  public static void AddValue(FlatBufferBuilder builder, bool value) { builder.AddBool(2, value, false); }
  public static Offset<SetDmxDeviceMode> EndSetDmxDeviceMode(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<SetDmxDeviceMode>(o);
  }
};


}
