// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.response
{

using global::System;
using global::FlatBuffers;

public struct AccountStatus : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static AccountStatus GetRootAsAccountStatus(ByteBuffer _bb) { return GetRootAsAccountStatus(_bb, new AccountStatus()); }
  public static AccountStatus GetRootAsAccountStatus(ByteBuffer _bb, AccountStatus obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public AccountStatus __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Balance { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int PreChargeBalance { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<AccountStatus> CreateAccountStatus(FlatBufferBuilder builder,
      int balance = 0,
      int preChargeBalance = 0) {
    builder.StartObject(2);
    AccountStatus.AddPreChargeBalance(builder, preChargeBalance);
    AccountStatus.AddBalance(builder, balance);
    return AccountStatus.EndAccountStatus(builder);
  }

  public static void StartAccountStatus(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddBalance(FlatBufferBuilder builder, int balance) { builder.AddInt(0, balance, 0); }
  public static void AddPreChargeBalance(FlatBufferBuilder builder, int preChargeBalance) { builder.AddInt(1, preChargeBalance, 0); }
  public static Offset<AccountStatus> EndAccountStatus(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<AccountStatus>(o);
  }
};


}
