// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.response
{

using global::System;
using global::FlatBuffers;

public struct AccountPreCharge : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static AccountPreCharge GetRootAsAccountPreCharge(ByteBuffer _bb) { return GetRootAsAccountPreCharge(_bb, new AccountPreCharge()); }
  public static AccountPreCharge GetRootAsAccountPreCharge(ByteBuffer _bb, AccountPreCharge obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public AccountPreCharge __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool Valid { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public int ChargeId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<AccountPreCharge> CreateAccountPreCharge(FlatBufferBuilder builder,
      bool valid = false,
      int chargeId = 0) {
    builder.StartObject(2);
    AccountPreCharge.AddChargeId(builder, chargeId);
    AccountPreCharge.AddValid(builder, valid);
    return AccountPreCharge.EndAccountPreCharge(builder);
  }

  public static void StartAccountPreCharge(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddValid(FlatBufferBuilder builder, bool valid) { builder.AddBool(0, valid, false); }
  public static void AddChargeId(FlatBufferBuilder builder, int chargeId) { builder.AddInt(1, chargeId, 0); }
  public static Offset<AccountPreCharge> EndAccountPreCharge(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<AccountPreCharge>(o);
  }
};


}
