// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.response
{

using global::System;
using global::FlatBuffers;

public struct AccountCharge : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static AccountCharge GetRootAsAccountCharge(ByteBuffer _bb) { return GetRootAsAccountCharge(_bb, new AccountCharge()); }
  public static AccountCharge GetRootAsAccountCharge(ByteBuffer _bb, AccountCharge obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public AccountCharge __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool Success { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<AccountCharge> CreateAccountCharge(FlatBufferBuilder builder,
      bool success = false) {
    builder.StartObject(1);
    AccountCharge.AddSuccess(builder, success);
    return AccountCharge.EndAccountCharge(builder);
  }

  public static void StartAccountCharge(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddSuccess(FlatBufferBuilder builder, bool success) { builder.AddBool(0, success, false); }
  public static Offset<AccountCharge> EndAccountCharge(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<AccountCharge>(o);
  }
};


}
