// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.response
{

using global::System;
using global::FlatBuffers;

public struct AddCredits : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static AddCredits GetRootAsAddCredits(ByteBuffer _bb) { return GetRootAsAddCredits(_bb, new AddCredits()); }
  public static AddCredits GetRootAsAddCredits(ByteBuffer _bb, AddCredits obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public AddCredits __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartAddCredits(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<AddCredits> EndAddCredits(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<AddCredits>(o);
  }
};


}
