// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.response
{

using global::System;
using global::FlatBuffers;

public struct AddDmxRuleSetting : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static AddDmxRuleSetting GetRootAsAddDmxRuleSetting(ByteBuffer _bb) { return GetRootAsAddDmxRuleSetting(_bb, new AddDmxRuleSetting()); }
  public static AddDmxRuleSetting GetRootAsAddDmxRuleSetting(ByteBuffer _bb, AddDmxRuleSetting obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public AddDmxRuleSetting __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint DeviceId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint SettingId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint RuleSettingId { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<AddDmxRuleSetting> CreateAddDmxRuleSetting(FlatBufferBuilder builder,
      uint deviceId = 0,
      uint settingId = 0,
      uint ruleSettingId = 0) {
    builder.StartObject(3);
    AddDmxRuleSetting.AddRuleSettingId(builder, ruleSettingId);
    AddDmxRuleSetting.AddSettingId(builder, settingId);
    AddDmxRuleSetting.AddDeviceId(builder, deviceId);
    return AddDmxRuleSetting.EndAddDmxRuleSetting(builder);
  }

  public static void StartAddDmxRuleSetting(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddDeviceId(FlatBufferBuilder builder, uint deviceId) { builder.AddUint(0, deviceId, 0); }
  public static void AddSettingId(FlatBufferBuilder builder, uint settingId) { builder.AddUint(1, settingId, 0); }
  public static void AddRuleSettingId(FlatBufferBuilder builder, uint ruleSettingId) { builder.AddUint(2, ruleSettingId, 0); }
  public static Offset<AddDmxRuleSetting> EndAddDmxRuleSetting(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<AddDmxRuleSetting>(o);
  }
};


}
