// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.response
{

using global::System;
using global::FlatBuffers;

public struct AddUser : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static AddUser GetRootAsAddUser(ByteBuffer _bb) { return GetRootAsAddUser(_bb, new AddUser()); }
  public static AddUser GetRootAsAddUser(ByteBuffer _bb, AddUser obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public AddUser __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint UId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<AddUser> CreateAddUser(FlatBufferBuilder builder,
      uint uId = 0) {
    builder.StartObject(1);
    AddUser.AddUId(builder, uId);
    return AddUser.EndAddUser(builder);
  }

  public static void StartAddUser(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddUId(FlatBufferBuilder builder, uint uId) { builder.AddUint(0, uId, 0); }
  public static Offset<AddUser> EndAddUser(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<AddUser>(o);
  }
};


}
