// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.response
{

using global::System;
using global::FlatBuffers;

public struct CalculateScore : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static CalculateScore GetRootAsCalculateScore(ByteBuffer _bb) { return GetRootAsCalculateScore(_bb, new CalculateScore()); }
  public static CalculateScore GetRootAsCalculateScore(ByteBuffer _bb, CalculateScore obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public CalculateScore __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public sisyfox.sisycol.Score? Data { get { int o = __p.__offset(4); return o != 0 ? (sisyfox.sisycol.Score?)(new sisyfox.sisycol.Score()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<CalculateScore> CreateCalculateScore(FlatBufferBuilder builder,
      Offset<sisyfox.sisycol.Score> dataOffset = default(Offset<sisyfox.sisycol.Score>)) {
    builder.StartObject(1);
    CalculateScore.AddData(builder, dataOffset);
    return CalculateScore.EndCalculateScore(builder);
  }

  public static void StartCalculateScore(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddData(FlatBufferBuilder builder, Offset<sisyfox.sisycol.Score> dataOffset) { builder.AddOffset(0, dataOffset.Value, 0); }
  public static Offset<CalculateScore> EndCalculateScore(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<CalculateScore>(o);
  }
};


}
