// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.response
{

using global::System;
using global::FlatBuffers;

public struct DmxDeviceSetting : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static DmxDeviceSetting GetRootAsDmxDeviceSetting(ByteBuffer _bb) { return GetRootAsDmxDeviceSetting(_bb, new DmxDeviceSetting()); }
  public static DmxDeviceSetting GetRootAsDmxDeviceSetting(ByteBuffer _bb, DmxDeviceSetting obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public DmxDeviceSetting __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
  public int StorageRef { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public uint RuleSettingCount { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public sbyte Norm { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetSbyte(o + __p.bb_pos) : (sbyte)0; } }
  public sbyte Value { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetSbyte(o + __p.bb_pos) : (sbyte)0; } }
  public sisyfox.sisycol.DmxDeviceSettingType Type { get { int o = __p.__offset(14); return o != 0 ? (sisyfox.sisycol.DmxDeviceSettingType)__p.bb.GetSbyte(o + __p.bb_pos) : sisyfox.sisycol.DmxDeviceSettingType.RANGE; } }

  public static Offset<DmxDeviceSetting> CreateDmxDeviceSetting(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset),
      int storageRef = 0,
      uint ruleSettingCount = 0,
      sbyte norm = 0,
      sbyte value = 0,
      sisyfox.sisycol.DmxDeviceSettingType type = sisyfox.sisycol.DmxDeviceSettingType.RANGE) {
    builder.StartObject(6);
    DmxDeviceSetting.AddRuleSettingCount(builder, ruleSettingCount);
    DmxDeviceSetting.AddStorageRef(builder, storageRef);
    DmxDeviceSetting.AddName(builder, nameOffset);
    DmxDeviceSetting.AddType(builder, type);
    DmxDeviceSetting.AddValue(builder, value);
    DmxDeviceSetting.AddNorm(builder, norm);
    return DmxDeviceSetting.EndDmxDeviceSetting(builder);
  }

  public static void StartDmxDeviceSetting(FlatBufferBuilder builder) { builder.StartObject(6); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static void AddStorageRef(FlatBufferBuilder builder, int storageRef) { builder.AddInt(1, storageRef, 0); }
  public static void AddRuleSettingCount(FlatBufferBuilder builder, uint ruleSettingCount) { builder.AddUint(2, ruleSettingCount, 0); }
  public static void AddNorm(FlatBufferBuilder builder, sbyte norm) { builder.AddSbyte(3, norm, 0); }
  public static void AddValue(FlatBufferBuilder builder, sbyte value) { builder.AddSbyte(4, value, 0); }
  public static void AddType(FlatBufferBuilder builder, sisyfox.sisycol.DmxDeviceSettingType type) { builder.AddSbyte(5, (sbyte)type, 0); }
  public static Offset<DmxDeviceSetting> EndDmxDeviceSetting(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<DmxDeviceSetting>(o);
  }
};


}
