// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.response
{

using global::System;
using global::FlatBuffers;

public struct EjectToken : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static EjectToken GetRootAsEjectToken(ByteBuffer _bb) { return GetRootAsEjectToken(_bb, new EjectToken()); }
  public static EjectToken GetRootAsEjectToken(ByteBuffer _bb, EjectToken obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public EjectToken __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Amount { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<EjectToken> CreateEjectToken(FlatBufferBuilder builder,
      uint amount = 0) {
    builder.StartObject(1);
    EjectToken.AddAmount(builder, amount);
    return EjectToken.EndEjectToken(builder);
  }

  public static void StartEjectToken(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddAmount(FlatBufferBuilder builder, uint amount) { builder.AddUint(0, amount, 0); }
  public static Offset<EjectToken> EndEjectToken(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<EjectToken>(o);
  }
};


}
