// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.response
{

using global::System;
using global::FlatBuffers;

public struct Error : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Error GetRootAsError(ByteBuffer _bb) { return GetRootAsError(_bb, new Error()); }
  public static Error GetRootAsError(ByteBuffer _bb, Error obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Error __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public sisyfox.sisycol.ErrorCode ErrorCode { get { int o = __p.__offset(4); return o != 0 ? (sisyfox.sisycol.ErrorCode)__p.bb.Get(o + __p.bb_pos) : sisyfox.sisycol.ErrorCode.BAD_TRANSMISSION; } }

  public static Offset<Error> CreateError(FlatBufferBuilder builder,
      sisyfox.sisycol.ErrorCode errorCode = sisyfox.sisycol.ErrorCode.BAD_TRANSMISSION) {
    builder.StartObject(1);
    Error.AddErrorCode(builder, errorCode);
    return Error.EndError(builder);
  }

  public static void StartError(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddErrorCode(FlatBufferBuilder builder, sisyfox.sisycol.ErrorCode errorCode) { builder.AddByte(0, (byte)errorCode, 0); }
  public static Offset<Error> EndError(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Error>(o);
  }
};


}
