// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.response
{

using global::System;
using global::FlatBuffers;

public struct GameUnlock : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static GameUnlock GetRootAsGameUnlock(ByteBuffer _bb) { return GetRootAsGameUnlock(_bb, new GameUnlock()); }
  public static GameUnlock GetRootAsGameUnlock(ByteBuffer _bb, GameUnlock obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public GameUnlock __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public GameUnlockResult ResultType { get { int o = __p.__offset(4); return o != 0 ? (GameUnlockResult)__p.bb.Get(o + __p.bb_pos) : GameUnlockResult.NONE; } }
  public TTable? Result<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(6); return o != 0 ? (TTable?)__p.__union<TTable>(o) : null; }

  public static Offset<GameUnlock> CreateGameUnlock(FlatBufferBuilder builder,
      GameUnlockResult result_type = GameUnlockResult.NONE,
      int resultOffset = 0) {
    builder.StartObject(2);
    GameUnlock.AddResult(builder, resultOffset);
    GameUnlock.AddResultType(builder, result_type);
    return GameUnlock.EndGameUnlock(builder);
  }

  public static void StartGameUnlock(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddResultType(FlatBufferBuilder builder, GameUnlockResult resultType) { builder.AddByte(0, (byte)resultType, 0); }
  public static void AddResult(FlatBufferBuilder builder, int resultOffset) { builder.AddOffset(1, resultOffset, 0); }
  public static Offset<GameUnlock> EndGameUnlock(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GameUnlock>(o);
  }
};


}
