// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.response
{

public enum GameUnlockResult : byte
{
 NONE = 0,
 GameUnlockComplete = 1,
 GameUnlockWait = 2,
};


}
