// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.response
{

using global::System;
using global::FlatBuffers;

public struct GameUnlockWait : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static GameUnlockWait GetRootAsGameUnlockWait(ByteBuffer _bb) { return GetRootAsGameUnlockWait(_bb, new GameUnlockWait()); }
  public static GameUnlockWait GetRootAsGameUnlockWait(ByteBuffer _bb, GameUnlockWait obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public GameUnlockWait __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public sisyfox.sisycol.GameBlockReason Reason { get { int o = __p.__offset(4); return o != 0 ? (sisyfox.sisycol.GameBlockReason)__p.bb.GetSbyte(o + __p.bb_pos) : sisyfox.sisycol.GameBlockReason.UNKNOWN; } }

  public static Offset<GameUnlockWait> CreateGameUnlockWait(FlatBufferBuilder builder,
      sisyfox.sisycol.GameBlockReason reason = sisyfox.sisycol.GameBlockReason.UNKNOWN) {
    builder.StartObject(1);
    GameUnlockWait.AddReason(builder, reason);
    return GameUnlockWait.EndGameUnlockWait(builder);
  }

  public static void StartGameUnlockWait(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddReason(FlatBufferBuilder builder, sisyfox.sisycol.GameBlockReason reason) { builder.AddSbyte(0, (sbyte)reason, 0); }
  public static Offset<GameUnlockWait> EndGameUnlockWait(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GameUnlockWait>(o);
  }
};


}
