// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.response
{

using global::System;
using global::FlatBuffers;

public struct GameUnlockComplete : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static GameUnlockComplete GetRootAsGameUnlockComplete(ByteBuffer _bb) { return GetRootAsGameUnlockComplete(_bb, new GameUnlockComplete()); }
  public static GameUnlockComplete GetRootAsGameUnlockComplete(ByteBuffer _bb, GameUnlockComplete obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public GameUnlockComplete __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool Success { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<GameUnlockComplete> CreateGameUnlockComplete(FlatBufferBuilder builder,
      bool success = false) {
    builder.StartObject(1);
    GameUnlockComplete.AddSuccess(builder, success);
    return GameUnlockComplete.EndGameUnlockComplete(builder);
  }

  public static void StartGameUnlockComplete(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddSuccess(FlatBufferBuilder builder, bool success) { builder.AddBool(0, success, false); }
  public static Offset<GameUnlockComplete> EndGameUnlockComplete(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GameUnlockComplete>(o);
  }
};


}
