// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.response
{

using global::System;
using global::FlatBuffers;

public struct GetDmxDeviceSetting : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static GetDmxDeviceSetting GetRootAsGetDmxDeviceSetting(ByteBuffer _bb) { return GetRootAsGetDmxDeviceSetting(_bb, new GetDmxDeviceSetting()); }
  public static GetDmxDeviceSetting GetRootAsGetDmxDeviceSetting(ByteBuffer _bb, GetDmxDeviceSetting obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public GetDmxDeviceSetting __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint DeviceId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint SettingId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public DmxDeviceSetting? Setting { get { int o = __p.__offset(8); return o != 0 ? (DmxDeviceSetting?)(new DmxDeviceSetting()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<GetDmxDeviceSetting> CreateGetDmxDeviceSetting(FlatBufferBuilder builder,
      uint deviceId = 0,
      uint settingId = 0,
      Offset<DmxDeviceSetting> settingOffset = default(Offset<DmxDeviceSetting>)) {
    builder.StartObject(3);
    GetDmxDeviceSetting.AddSetting(builder, settingOffset);
    GetDmxDeviceSetting.AddSettingId(builder, settingId);
    GetDmxDeviceSetting.AddDeviceId(builder, deviceId);
    return GetDmxDeviceSetting.EndGetDmxDeviceSetting(builder);
  }

  public static void StartGetDmxDeviceSetting(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddDeviceId(FlatBufferBuilder builder, uint deviceId) { builder.AddUint(0, deviceId, 0); }
  public static void AddSettingId(FlatBufferBuilder builder, uint settingId) { builder.AddUint(1, settingId, 0); }
  public static void AddSetting(FlatBufferBuilder builder, Offset<DmxDeviceSetting> settingOffset) { builder.AddOffset(2, settingOffset.Value, 0); }
  public static Offset<GetDmxDeviceSetting> EndGetDmxDeviceSetting(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GetDmxDeviceSetting>(o);
  }
};


}
