// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.response
{

using global::System;
using global::FlatBuffers;

public struct GetDmxRuleRangeSetting : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static GetDmxRuleRangeSetting GetRootAsGetDmxRuleRangeSetting(ByteBuffer _bb) { return GetRootAsGetDmxRuleRangeSetting(_bb, new GetDmxRuleRangeSetting()); }
  public static GetDmxRuleRangeSetting GetRootAsGetDmxRuleRangeSetting(ByteBuffer _bb, GetDmxRuleRangeSetting obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public GetDmxRuleRangeSetting __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint DeviceId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint SettingId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint RuleSettingId { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public sisyfox.sisycol.DmxRuleRangeSetting? RuleSetting { get { int o = __p.__offset(10); return o != 0 ? (sisyfox.sisycol.DmxRuleRangeSetting?)(new sisyfox.sisycol.DmxRuleRangeSetting()).__assign(o + __p.bb_pos, __p.bb) : null; } }

  public static void StartGetDmxRuleRangeSetting(FlatBufferBuilder builder) { builder.StartObject(4); }
  public static void AddDeviceId(FlatBufferBuilder builder, uint deviceId) { builder.AddUint(0, deviceId, 0); }
  public static void AddSettingId(FlatBufferBuilder builder, uint settingId) { builder.AddUint(1, settingId, 0); }
  public static void AddRuleSettingId(FlatBufferBuilder builder, uint ruleSettingId) { builder.AddUint(2, ruleSettingId, 0); }
  public static void AddRuleSetting(FlatBufferBuilder builder, Offset<sisyfox.sisycol.DmxRuleRangeSetting> ruleSettingOffset) { builder.AddStruct(3, ruleSettingOffset.Value, 0); }
  public static Offset<GetDmxRuleRangeSetting> EndGetDmxRuleRangeSetting(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GetDmxRuleRangeSetting>(o);
  }
};


}
