// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.response
{

using global::System;
using global::FlatBuffers;

public struct GetDmxDeviceChannelRange : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static GetDmxDeviceChannelRange GetRootAsGetDmxDeviceChannelRange(ByteBuffer _bb) { return GetRootAsGetDmxDeviceChannelRange(_bb, new GetDmxDeviceChannelRange()); }
  public static GetDmxDeviceChannelRange GetRootAsGetDmxDeviceChannelRange(ByteBuffer _bb, GetDmxDeviceChannelRange obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public GetDmxDeviceChannelRange __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint DeviceId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint ChannelId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public sisyfox.sisycol.DmxDeviceChannel? Channel(int j) { int o = __p.__offset(8); return o != 0 ? (sisyfox.sisycol.DmxDeviceChannel?)(new sisyfox.sisycol.DmxDeviceChannel()).__assign(__p.__vector(o) + j * 16, __p.bb) : null; }
  public int ChannelLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<GetDmxDeviceChannelRange> CreateGetDmxDeviceChannelRange(FlatBufferBuilder builder,
      uint deviceId = 0,
      uint channelId = 0,
      VectorOffset channelOffset = default(VectorOffset)) {
    builder.StartObject(3);
    GetDmxDeviceChannelRange.AddChannel(builder, channelOffset);
    GetDmxDeviceChannelRange.AddChannelId(builder, channelId);
    GetDmxDeviceChannelRange.AddDeviceId(builder, deviceId);
    return GetDmxDeviceChannelRange.EndGetDmxDeviceChannelRange(builder);
  }

  public static void StartGetDmxDeviceChannelRange(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddDeviceId(FlatBufferBuilder builder, uint deviceId) { builder.AddUint(0, deviceId, 0); }
  public static void AddChannelId(FlatBufferBuilder builder, uint channelId) { builder.AddUint(1, channelId, 0); }
  public static void AddChannel(FlatBufferBuilder builder, VectorOffset channelOffset) { builder.AddOffset(2, channelOffset.Value, 0); }
  public static void StartChannelVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(16, numElems, 4); }
  public static Offset<GetDmxDeviceChannelRange> EndGetDmxDeviceChannelRange(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GetDmxDeviceChannelRange>(o);
  }
};


}
