// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.response
{

using global::System;
using global::FlatBuffers;

public struct GetDmxRuleRangeSettingRange : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static GetDmxRuleRangeSettingRange GetRootAsGetDmxRuleRangeSettingRange(ByteBuffer _bb) { return GetRootAsGetDmxRuleRangeSettingRange(_bb, new GetDmxRuleRangeSettingRange()); }
  public static GetDmxRuleRangeSettingRange GetRootAsGetDmxRuleRangeSettingRange(ByteBuffer _bb, GetDmxRuleRangeSettingRange obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public GetDmxRuleRangeSettingRange __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint DeviceId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint SettingId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint RuleSettingId { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public sisyfox.sisycol.DmxRuleRangeSetting? RuleSetting(int j) { int o = __p.__offset(10); return o != 0 ? (sisyfox.sisycol.DmxRuleRangeSetting?)(new sisyfox.sisycol.DmxRuleRangeSetting()).__assign(__p.__vector(o) + j * 28, __p.bb) : null; }
  public int RuleSettingLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<GetDmxRuleRangeSettingRange> CreateGetDmxRuleRangeSettingRange(FlatBufferBuilder builder,
      uint deviceId = 0,
      uint settingId = 0,
      uint ruleSettingId = 0,
      VectorOffset ruleSettingOffset = default(VectorOffset)) {
    builder.StartObject(4);
    GetDmxRuleRangeSettingRange.AddRuleSetting(builder, ruleSettingOffset);
    GetDmxRuleRangeSettingRange.AddRuleSettingId(builder, ruleSettingId);
    GetDmxRuleRangeSettingRange.AddSettingId(builder, settingId);
    GetDmxRuleRangeSettingRange.AddDeviceId(builder, deviceId);
    return GetDmxRuleRangeSettingRange.EndGetDmxRuleRangeSettingRange(builder);
  }

  public static void StartGetDmxRuleRangeSettingRange(FlatBufferBuilder builder) { builder.StartObject(4); }
  public static void AddDeviceId(FlatBufferBuilder builder, uint deviceId) { builder.AddUint(0, deviceId, 0); }
  public static void AddSettingId(FlatBufferBuilder builder, uint settingId) { builder.AddUint(1, settingId, 0); }
  public static void AddRuleSettingId(FlatBufferBuilder builder, uint ruleSettingId) { builder.AddUint(2, ruleSettingId, 0); }
  public static void AddRuleSetting(FlatBufferBuilder builder, VectorOffset ruleSettingOffset) { builder.AddOffset(3, ruleSettingOffset.Value, 0); }
  public static void StartRuleSettingVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(28, numElems, 4); }
  public static Offset<GetDmxRuleRangeSettingRange> EndGetDmxRuleRangeSettingRange(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GetDmxRuleRangeSettingRange>(o);
  }
};


}
