// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.response
{

using global::System;
using global::FlatBuffers;

public struct GetIdealTime : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static GetIdealTime GetRootAsGetIdealTime(ByteBuffer _bb) { return GetRootAsGetIdealTime(_bb, new GetIdealTime()); }
  public static GetIdealTime GetRootAsGetIdealTime(ByteBuffer _bb, GetIdealTime obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public GetIdealTime __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Time { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<GetIdealTime> CreateGetIdealTime(FlatBufferBuilder builder,
      uint time = 0) {
    builder.StartObject(1);
    GetIdealTime.AddTime(builder, time);
    return GetIdealTime.EndGetIdealTime(builder);
  }

  public static void StartGetIdealTime(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddTime(FlatBufferBuilder builder, uint time) { builder.AddUint(0, time, 0); }
  public static Offset<GetIdealTime> EndGetIdealTime(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GetIdealTime>(o);
  }
};


}
