// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.response
{

using global::System;
using global::FlatBuffers;

public struct GetRemoteDevices : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static GetRemoteDevices GetRootAsGetRemoteDevices(ByteBuffer _bb) { return GetRootAsGetRemoteDevices(_bb, new GetRemoteDevices()); }
  public static GetRemoteDevices GetRootAsGetRemoteDevices(ByteBuffer _bb, GetRemoteDevices obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public GetRemoteDevices __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Device? Devices(int j) { int o = __p.__offset(4); return o != 0 ? (Device?)(new Device()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DevicesLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<GetRemoteDevices> CreateGetRemoteDevices(FlatBufferBuilder builder,
      VectorOffset devicesOffset = default(VectorOffset)) {
    builder.StartObject(1);
    GetRemoteDevices.AddDevices(builder, devicesOffset);
    return GetRemoteDevices.EndGetRemoteDevices(builder);
  }

  public static void StartGetRemoteDevices(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddDevices(FlatBufferBuilder builder, VectorOffset devicesOffset) { builder.AddOffset(0, devicesOffset.Value, 0); }
  public static VectorOffset CreateDevicesVector(FlatBufferBuilder builder, Offset<Device>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartDevicesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<GetRemoteDevices> EndGetRemoteDevices(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GetRemoteDevices>(o);
  }
};


}
