// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.response
{

using global::System;
using global::FlatBuffers;

public struct GetScore : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static GetScore GetRootAsGetScore(ByteBuffer _bb) { return GetRootAsGetScore(_bb, new GetScore()); }
  public static GetScore GetRootAsGetScore(ByteBuffer _bb, GetScore obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public GetScore __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public sisyfox.sisycol.Score? Data { get { int o = __p.__offset(4); return o != 0 ? (sisyfox.sisycol.Score?)(new sisyfox.sisycol.Score()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<GetScore> CreateGetScore(FlatBufferBuilder builder,
      Offset<sisyfox.sisycol.Score> dataOffset = default(Offset<sisyfox.sisycol.Score>)) {
    builder.StartObject(1);
    GetScore.AddData(builder, dataOffset);
    return GetScore.EndGetScore(builder);
  }

  public static void StartGetScore(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddData(FlatBufferBuilder builder, Offset<sisyfox.sisycol.Score> dataOffset) { builder.AddOffset(0, dataOffset.Value, 0); }
  public static Offset<GetScore> EndGetScore(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GetScore>(o);
  }
};


}
