// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.response
{

using global::System;
using global::FlatBuffers;

public struct GetSettings : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static GetSettings GetRootAsGetSettings(ByteBuffer _bb) { return GetRootAsGetSettings(_bb, new GetSettings()); }
  public static GetSettings GetRootAsGetSettings(ByteBuffer _bb, GetSettings obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public GetSettings __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public sisyfox.sisycol.Setting? Settings(int j) { int o = __p.__offset(4); return o != 0 ? (sisyfox.sisycol.Setting?)(new sisyfox.sisycol.Setting()).__assign(__p.__vector(o) + j * 8, __p.bb) : null; }
  public int SettingsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<GetSettings> CreateGetSettings(FlatBufferBuilder builder,
      VectorOffset settingsOffset = default(VectorOffset)) {
    builder.StartObject(1);
    GetSettings.AddSettings(builder, settingsOffset);
    return GetSettings.EndGetSettings(builder);
  }

  public static void StartGetSettings(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddSettings(FlatBufferBuilder builder, VectorOffset settingsOffset) { builder.AddOffset(0, settingsOffset.Value, 0); }
  public static void StartSettingsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(8, numElems, 4); }
  public static Offset<GetSettings> EndGetSettings(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GetSettings>(o);
  }
};


}
