// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.response
{

using global::System;
using global::FlatBuffers;

public struct GetSettings : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static GetSettings GetRootAsGetSettings(ByteBuffer _bb) { return GetRootAsGetSettings(_bb, new GetSettings()); }
  public static GetSettings GetRootAsGetSettings(ByteBuffer _bb, GetSettings obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public GetSettings __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public sisyfox.sisycol.GeneralSetting? GeneralSetting { get { int o = __p.__offset(4); return o != 0 ? (sisyfox.sisycol.GeneralSetting?)(new sisyfox.sisycol.GeneralSetting()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public sisyfox.sisycol.UserSetting? UserSetting { get { int o = __p.__offset(6); return o != 0 ? (sisyfox.sisycol.UserSetting?)(new sisyfox.sisycol.UserSetting()).__assign(o + __p.bb_pos, __p.bb) : null; } }

  public static void StartGetSettings(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddGeneralSetting(FlatBufferBuilder builder, Offset<sisyfox.sisycol.GeneralSetting> generalSettingOffset) { builder.AddStruct(0, generalSettingOffset.Value, 0); }
  public static void AddUserSetting(FlatBufferBuilder builder, Offset<sisyfox.sisycol.UserSetting> userSettingOffset) { builder.AddStruct(1, userSettingOffset.Value, 0); }
  public static Offset<GetSettings> EndGetSettings(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GetSettings>(o);
  }
};


}
