// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.response
{

using global::System;
using global::FlatBuffers;

public struct Info : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Info GetRootAsInfo(ByteBuffer _bb) { return GetRootAsInfo(_bb, new Info()); }
  public static Info GetRootAsInfo(ByteBuffer _bb, Info obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Info __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public sisyfox.sisycol.Version? Version { get { int o = __p.__offset(4); return o != 0 ? (sisyfox.sisycol.Version?)(new sisyfox.sisycol.Version()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public uint ServerVersion { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)4294967295; } }
  public uint ScoreCount { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)4294967295; } }
  public uint UserCount { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)4294967295; } }
  public uint DmxDeviceCount { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)4294967295; } }
  public uint RegistryEntryCount { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)4294967295; } }
  public uint UserId { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)4294967295; } }

  public static void StartInfo(FlatBufferBuilder builder) { builder.StartObject(7); }
  public static void AddVersion(FlatBufferBuilder builder, Offset<sisyfox.sisycol.Version> versionOffset) { builder.AddStruct(0, versionOffset.Value, 0); }
  public static void AddServerVersion(FlatBufferBuilder builder, uint serverVersion) { builder.AddUint(1, serverVersion, 4294967295); }
  public static void AddScoreCount(FlatBufferBuilder builder, uint scoreCount) { builder.AddUint(2, scoreCount, 4294967295); }
  public static void AddUserCount(FlatBufferBuilder builder, uint userCount) { builder.AddUint(3, userCount, 4294967295); }
  public static void AddDmxDeviceCount(FlatBufferBuilder builder, uint dmxDeviceCount) { builder.AddUint(4, dmxDeviceCount, 4294967295); }
  public static void AddRegistryEntryCount(FlatBufferBuilder builder, uint registryEntryCount) { builder.AddUint(5, registryEntryCount, 4294967295); }
  public static void AddUserId(FlatBufferBuilder builder, uint userId) { builder.AddUint(6, userId, 4294967295); }
  public static Offset<Info> EndInfo(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Info>(o);
  }
};


}
