// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.response
{

using global::System;
using global::FlatBuffers;

public struct PayPerPlayStatistic_DEPRECATED : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static PayPerPlayStatistic_DEPRECATED GetRootAsPayPerPlayStatistic_DEPRECATED(ByteBuffer _bb) { return GetRootAsPayPerPlayStatistic_DEPRECATED(_bb, new PayPerPlayStatistic_DEPRECATED()); }
  public static PayPerPlayStatistic_DEPRECATED GetRootAsPayPerPlayStatistic_DEPRECATED(ByteBuffer _bb, PayPerPlayStatistic_DEPRECATED obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public PayPerPlayStatistic_DEPRECATED __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Timestamp { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public uint GeneratedCredits { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint AcceptedMoney { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint CreditsWorth { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<PayPerPlayStatistic_DEPRECATED> CreatePayPerPlayStatistic_DEPRECATED(FlatBufferBuilder builder,
      ulong timestamp = 0,
      uint generated_credits = 0,
      uint accepted_money = 0,
      uint credits_worth = 0) {
    builder.StartObject(4);
    PayPerPlayStatistic_DEPRECATED.AddTimestamp(builder, timestamp);
    PayPerPlayStatistic_DEPRECATED.AddCreditsWorth(builder, credits_worth);
    PayPerPlayStatistic_DEPRECATED.AddAcceptedMoney(builder, accepted_money);
    PayPerPlayStatistic_DEPRECATED.AddGeneratedCredits(builder, generated_credits);
    return PayPerPlayStatistic_DEPRECATED.EndPayPerPlayStatistic_DEPRECATED(builder);
  }

  public static void StartPayPerPlayStatistic_DEPRECATED(FlatBufferBuilder builder) { builder.StartObject(4); }
  public static void AddTimestamp(FlatBufferBuilder builder, ulong timestamp) { builder.AddUlong(0, timestamp, 0); }
  public static void AddGeneratedCredits(FlatBufferBuilder builder, uint generatedCredits) { builder.AddUint(1, generatedCredits, 0); }
  public static void AddAcceptedMoney(FlatBufferBuilder builder, uint acceptedMoney) { builder.AddUint(2, acceptedMoney, 0); }
  public static void AddCreditsWorth(FlatBufferBuilder builder, uint creditsWorth) { builder.AddUint(3, creditsWorth, 0); }
  public static Offset<PayPerPlayStatistic_DEPRECATED> EndPayPerPlayStatistic_DEPRECATED(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<PayPerPlayStatistic_DEPRECATED>(o);
  }
};


}
