// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.response
{

using global::System;
using global::FlatBuffers;

public struct RemoveDmxDeviceSetting : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static RemoveDmxDeviceSetting GetRootAsRemoveDmxDeviceSetting(ByteBuffer _bb) { return GetRootAsRemoveDmxDeviceSetting(_bb, new RemoveDmxDeviceSetting()); }
  public static RemoveDmxDeviceSetting GetRootAsRemoveDmxDeviceSetting(ByteBuffer _bb, RemoveDmxDeviceSetting obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public RemoveDmxDeviceSetting __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint DeviceId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint SettingId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<RemoveDmxDeviceSetting> CreateRemoveDmxDeviceSetting(FlatBufferBuilder builder,
      uint deviceId = 0,
      uint settingId = 0) {
    builder.StartObject(2);
    RemoveDmxDeviceSetting.AddSettingId(builder, settingId);
    RemoveDmxDeviceSetting.AddDeviceId(builder, deviceId);
    return RemoveDmxDeviceSetting.EndRemoveDmxDeviceSetting(builder);
  }

  public static void StartRemoveDmxDeviceSetting(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddDeviceId(FlatBufferBuilder builder, uint deviceId) { builder.AddUint(0, deviceId, 0); }
  public static void AddSettingId(FlatBufferBuilder builder, uint settingId) { builder.AddUint(1, settingId, 0); }
  public static Offset<RemoveDmxDeviceSetting> EndRemoveDmxDeviceSetting(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<RemoveDmxDeviceSetting>(o);
  }
};


}
