// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.response
{

using global::System;
using global::FlatBuffers;

public struct SetSetting : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static SetSetting GetRootAsSetSetting(ByteBuffer _bb) { return GetRootAsSetSetting(_bb, new SetSetting()); }
  public static SetSetting GetRootAsSetSetting(ByteBuffer _bb, SetSetting obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public SetSetting __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public sisyfox.sisycol.Setting? Setting { get { int o = __p.__offset(4); return o != 0 ? (sisyfox.sisycol.Setting?)(new sisyfox.sisycol.Setting()).__assign(o + __p.bb_pos, __p.bb) : null; } }

  public static void StartSetSetting(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddSetting(FlatBufferBuilder builder, Offset<sisyfox.sisycol.Setting> settingOffset) { builder.AddStruct(0, settingOffset.Value, 0); }
  public static Offset<SetSetting> EndSetSetting(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<SetSetting>(o);
  }
};


}
