// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace sisyfox.sisycol.response
{

using global::System;
using global::FlatBuffers;

public struct SuspendSystem : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static SuspendSystem GetRootAsSuspendSystem(ByteBuffer _bb) { return GetRootAsSuspendSystem(_bb, new SuspendSystem()); }
  public static SuspendSystem GetRootAsSuspendSystem(ByteBuffer _bb, SuspendSystem obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public SuspendSystem __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartSuspendSystem(FlatBufferBuilder builder) { builder.StartObject(0); }
  public static Offset<SuspendSystem> EndSuspendSystem(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<SuspendSystem>(o);
  }
};


}
